### ISSUE TITLE
check that /transfer address is a bitcoin address and not the same as user address

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#100]
It might sound stupid but this is a common error (probably because of a copy-paste mess) Also. I would be a nice opportunity to send the user a joke about sending his money to the same wallet.

**Comment by Xeyler** [comment]
What does sending bitcoin to yourself do?

**Comment by CubeFromSpace** [comment]
This could be added by checking the recipient and the sender of the bitcoins. Then check for a match, and prevent matched transactions. (I'll leave the coding to you, I can only just read the Java, which I don't know well)

**Comment by CubeFromSpace** [comment]
@explodi is this issue valid with the 2000b minimum and new Xapo stuff? (Just wondering)

**Comment by Shiny-andKittens** [comment]
I will try to fix this, @Xeyler

**Comment by Shiny-andKittens** [comment]
@xeyler @explodi this is no longer an issue with 2000b minimum and internal system
