### ISSUE TITLE
Allowing the Witherboss

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#101]
Maybe Witherboss is disabled.  If explosive damage is off, and now many players are higher level, Witherboss might be a good challenge for the players.  Maybe there is a way to set a level cap on it to prevent an impossibly high level one from spawning.  Having no experience fighting this boss, any other suggestions welcome.  Enabling it now, would be just in time for Halloween and great start to Bitquest season.

**Comment by Airiellis** [comment]
Agree. This is easy to help mods have events.

**Comment by CubeFromSpace** [comment]
This could be allowed, but I think it should eventually despawn if not killed

**Comment by Burntuno** [comment]
I think withers spawn fine.  They did work for Airellis.  I need to run more tests.  It is just hard to collect the heads.  I will update this soon.

**Comment by CubeFromSpace** [comment]
Maybe on Beta server with some admins.

**Comment by CubeFromSpace** [comment]
Now that I've found out, the wither is enabled, as a player bk216 was spawning some and killing them. This issue is invalid.

**Comment by CubeFromSpace** [comment]
@burntuno the wither is working
