### ISSUE TITLE
Moderators could reset mobless areas to allow towns and regions to have a battle zone.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#102]
This would be better to keep simple and still have same decay.  It would let the Moderator inspect area to make sure it is open for public use not just a personal grind factory.  Most enhancements to code should be automatic in design so if neglected for periods of time, things can settle into approved states.  Overworld mob burnout is the final default state, until all could be examined and reset again.

**Comment by Airiellis** [comment]
This would help Satoshi area so much. New players come to the game and can't find mobs for loot and items.

**Comment by CubeFromSpace** [comment]
Maybe allow it to spawn from spawners, and hide the spawners in the sewers and nether dungeon

**Comment by CubeFromSpace** [comment]
This kinda happened when @explodi updated to 1.11.2

**Comment by CubeFromSpace** [comment]
Is the mob burnout necessary? Kinda removes the "RPG" feel from RPGMMO. In an RPG, all the mobs somehow come back (in some form, whether it respawns or he new Zelda game has a blood moon)

We should also avoid the mobs being to close, though, because new players may be killed by mobs (and Satoshi has that "pure" feel (maybe because of all the quartz))

@raccoonbear, any suggestions about how it won't work? (Not trying to be smartaleik, actually need opinions)

**Comment by Shiny-andKittens** [comment]
Maybe I could make it so low-level mobs appear if the Landname is Satoshi. @Burntuno does this make sense?

**Comment by Burntuno** [comment]
We don't need mobs in Satoshi.  Actually if a player can't travel 300 blocks out to find mobs or take a rail to distant unexplored land, then they aren't trying hard enough.  Mobs in the last couple of builds have been spawning strong, where needed.  These issues plagued game more on early builds.  Still a way for Moderators to control mobs would be up to Administration and it is not a priority.  Other issues and bugs should be investigated first.  Remember low level mobs will make it more easy for non Minecraft playing bit farmers to abuse the system.  We would never want it so a player can just join, right away make 2000 bits and leave.  Actually if it seems hard, maybe they would deposit for some advantage, and that is better for the server.  They should be inclined to explore, build, join friends, and gear up, to start to win bits.
