### ISSUE TITLE
Possible way to reduce burden and fund Miner Fee Wallet.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#103]
Not sure if possible, but this could help.  Keep the Loots, Plots and Shops all on the Miner Fee Wallet.  Have the Player to Player in game wallet transactions (like when a Player uses name as address) use the Miner Fee Wallet, like currently.  When a player uses an actual Bitcoin address, signaling an external transfer, charge a fixed 200 bit withdrawal Miner Fee.  Somehow use Blockcypher's Fee estimate system to take proper amount (usually 64 to 150 bits) from the 200 withdrawal fee and send the remainder to the Miner Fee Wallet.  This might be possible by sending the 200 bits to Miner Fee address as part of transaction, allowing wallet API to subtract appropriate fee, all within the same wallet interaction.  If this could be done in the same instance, hopefully not many more bytes are added to the transaction size.  This could also help discourage inappropriate wallet use and prevent player withdraw after every win, which has a double impact on Miner Fee Wallet.

**Comment by Airiellis** [comment]
Great idea.

**Comment by CubeFromSpace** [comment]
I agree. It further reinforces the economy of the server, and adds an atmosphere of real world taxes. And yeah, it will support the server.

**Comment by Burntuno** [comment]
I have a good feeling that if API is flexible to include 2 parts in a TX and one of them was a fixed 200 bit split off the main transaction directed at the Fee Wallet, Fee wallet would adjust to proper fee and create new output with remainder to use for other transactions.  This is over my head, but I'm trying to be creative.  Currently Fee Wallet is well funded and maybe it shouldn't have too many outputs, but I definitely like idea of 200 bit external withdrawal fee.  It would cut down on the fake accounts coming in for one score.  I think this happens once in a while.  All ingame stuff should still be no charge.  Only charge when they are withdrawing to an actual BTC address.

**Comment by theraccoonbear** [comment]
I think fees for **every** transfer of funds (land buy, villager purchase, P2P, to external wallet) should be completely paid for by the player.  Nothing else is sustainable long-term.  All in-game prices should be increased to reflect the actual costs, or someone else (like you or I) are subsidizing others' play.

**Comment by CubeFromSpace** [comment]
Was this fixed? @explodi added the Xapo system and all
