### ISSUE TITLE
Alternate level progress indication.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#104]
This idea is from player coolred60.  Since normal level progress indication is broken from the custom leveling, maybe we can have a /levelprogress (or just /level) command.  This could show current level status and how much more needed to next level.  Maybe add a few other statistics also to make it more useful.

**Comment by CubeFromSpace** [comment]
This could also be in the thing that says your Balance on the side of the screen

**Comment by Burntuno** [comment]
Good idea.  Real-estate on screen is very pricey for some, so keeping anything added streamlined is recommended.

**Comment by juanj** [comment]
What you guys think about this?
![2016-11-04_21 15 16](https://cloud.githubusercontent.com/assets/1958175/20026940/fa8a21c8-a2d3-11e6-9b3b-7c3f5a7dde18.png)

**Comment by juanj** [comment]
In #111 I created a PR for this. In that PR I also fixed the xp system.

So now I'm thinking... this still necessary? Because the player xp bar now is accurate.
Maybe we can think in other kind of info to show in the scoreboard.

**Comment by Burntuno** [comment]
Nice. Idea was good, but fixing level indication was main goal.  Does it still accurately show for the higher level players? like 30 or 50?  That is when most wrong.  Score board simple and small is best for now, until another good idea comes up.  Thanks Juanj!

**Comment by CubeFromSpace** [comment]
That looks nice 👍

**Comment by juanj** [comment]
Since the xp bar is now working, this is no longer necessary.
