### ISSUE TITLE
Villager can take your item and it is lost.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#105]
If a villager shop is open, and an item is accidently placed into the shopping inventory slots, it is lost.  There must be a way to prevent item from being placed in this area, weather dragged and dropped there, or accidently shift clicked there.  Reported incident is from pressing 1 and it took item from hot bar to villager Inventory.  This would need to be avoided also.

**Comment by juanj** [comment]
The only case when this happens is if you have the mouse cursor in one of the villager empty slots and press one of your items shortcut.
Right now the logic of the villager market is handled in `InventoryClickEvent` and all the event that are not buying something are canceled. But the case described above is not a click event.

**Comment by CubeFromSpace** [comment]
It could be that you need to add a click event cancel for anything other than from the villager inventory.

**Comment by CubeFromSpace** [comment]
Now I experimented some, and I saw that it wouldn't let me move my inventory items at all. (Actually it did once, that was when I had a 4000ms ping.)

**Comment by CubeFromSpace** [comment]
Maybe prevent hot bar changes. If hotbar updates are cancelled in villager menu, maybe you can't use keyboard shortcuts

**Comment by CubeFromSpace** [comment]
This was fixed :P

**Comment by syrianrue** [comment]
http://i.imgur.com/8l7gWLG.png

i dont think this is fixed. take a look at the arrow in the bottom center that used to be mine.

**Comment by CubeFromSpace** [comment]
It was attempted to be fixed
