### ISSUE TITLE
Increase view distance.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#106]
Leading animal, riding carts, flying Eltra, etc. have way less noticeable lag.  Maybe the view distance can be increased.   This could create a better game experience and maybe draw some players back to the game.

**Comment by Burntuno** [comment]
Even one more level of increase would be a great percentage of change compared to how low it is now.

**Comment by theraccoonbear** [comment]
I think the biggest issue is that increasing view distance requires keeping more chunks loaded (if I understand the mechanism correctly), and the number of chunks loaded is the square of the view distance.  The computational requirements increase significantly with each chunk of view distance increasing since those chunks are fully loaded and updating (mobs, plant growth, water flow, redstone tick, etc, etc).  Here's short breakdown of the impact:

|| View Distance || Chunks Loaded ||
|1 | 1|
|2 | 4|
|3 | 9|
|4 | 16|
|5 | 25|
|6 | 36|
|7 | 49|
|8 | 64|
|9 | 81|
|10 | 100|
|11 | 121|
|12 | 144|
|13 | 169|
|14 | 196|
|15 | 225|
|16 | 256|
|17 | 289|
|18 | 324|

**Comment by theraccoonbear** [comment]
hmm, no table support I guess :(

**Comment by CubeFromSpace** [comment]
So, how much is the view distance now, and how much could it handle?

**Comment by theraccoonbear** [comment]
It's fairly low now.  maybe 4 or 5?  how much it could handle, I don't know.  Maybe @explodi or someone more familiar with the system it runs on could comment.

**Comment by theraccoonbear** [comment]
Also, my math was wrong before. I believe it's actually worse...

a view distance of 1 requires 9 chunks to be loaded
a view distance of 2 requires 16 chunks to be loaded
a view distance of 3 requires 25 chunks to be loaded
a view distance of 4 requires 36 chunks to be loaded
a view distance of 5 requires 49 chunks to be loaded
a view distance of 6 requires 64 chunks to be loaded
a view distance of 7 requires 81 chunks to be loaded
a view distance of 8 requires 100 chunks to be loaded
a view distance of 9 requires 121 chunks to be loaded
a view distance of 10 requires 144 chunks to be loaded
a view distance of 11 requires 169 chunks to be loaded
a view distance of 12 requires 196 chunks to be loaded
a view distance of 13 requires 225 chunks to be loaded
a view distance of 14 requires 256 chunks to be loaded
a view distance of 15 requires 289 chunks to be loaded
a view distance of 16 requires 324 chunks to be loaded
a view distance of 17 requires 361 chunks to be loaded
a view distance of 18 requires 400 chunks to be loaded

**Comment by CubeFromSpace** [comment]
Can the server take more than 4 or 5? I think this could be tested on the Beta server

**Comment by theraccoonbear** [comment]
I think beta would not be a great test for this.  At a minimum, if it doesn't have the same hardware or virtualization specs, and doesn't have roughly the same number of users playing, you're not going to get a good picture of how increased chunk loading (and thus tick updating) affects the server.  If nothing else, this is also an instance-specific configuration issue, and not a code issue, so it might be better discussing on the Slack and encouraging those like @explodi, who may have access to those configurations, to try increasing render distance.

**Comment by Shiny-andKittens** [comment]
@burntuno right now we have lag again

**Comment by Shiny-andKittens** [comment]
@explodi what is your opinion on this?
