### ISSUE TITLE
Events (suggestion)

### ISSUE THREAD

**Issue by CubeFromSpace** [bitquest/bitquest#108]
Like in terraria, random events that occur, like maybe slimes spawning rapidly or zombies spawning everywhere. Of course, it can be more that those two

**Comment by Burntuno** [comment]
Yes, it would be good to have more Boss type mobs to fight in BQ.  Like low level mobs in Satoshi Sewers, regions with giant or small mobs, or town arenas the spawn all kinds of mobs.

**Comment by CubeFromSpace** [comment]
I think that mobs aren't in the sewers because of the protected zones where mobs don't spawn. Maybe some specific zones, such as x y z sectors instead of x z sectors, could be identified as "dungeon zones" where special mobs spawn.
