### ISSUE TITLE
Add back end (suggestion)

### ISSUE THREAD

**Issue by CubeFromSpace** [bitquest/bitquest#110]
I know that the end was disabled at some point, but is it possible to re-add it? If not, why was it removed and why can't it be re-added?

**Comment by Burntuno** [comment]
End is planned for future use.  Of course, future may never turns out as intended.  Once we have something decided, it may be of use.

**Comment by CubeFromSpace** [comment]
Ok, maybe it can be used for grinding, like Nether. There apparently used to be an End, and I actually think you told me that on the server.

**Comment by CubeFromSpace** [comment]
I think it is just that the portal is closed, I'll leave this to the developers
