### ISSUE TITLE
Need the 200 bit Minimum added back to code.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#113]
There needs to be a way to stop and warn players that wallet minimum is 200 bits.

**Comment by CubeFromSpace** [comment]
That makes sense, maybe check the transaction amount and cancel transactions less than 200b

**Comment by Burntuno** [comment]
Main reason is Miner Fees.  Miner Fees cost 60 to 150 bits for 1 transaction, no matter the amount.  If players start sending 20 bit transactions, costing server more than 60 bits, it would drain Fees Wallet.  Since loots are 200 bits and claims are 200 bits, it just makes sense to keep minimum transfers at 200 bits also.  In another Issue, it is suggested we make a player paid 200 bit fee on off site withdraws, to help prevent those who win, withdraw, win, withdraw.  This happens and has a 2X affect on Miner Fees used.

**Comment by CubeFromSpace** [comment]
This is related somewhat to your other issue #103. And I agree with both of these issues, because I think miner transaction fees should be payed for by players.

**Comment by CubeFromSpace** [comment]
I might be able to make a PR, if someone would explain the syntax of wallet.java to me XD

**Comment by CubeFromSpace** [comment]
Can anyone tell me how to PR? I've never done it before, and I have a solution to this.

**Comment by CubeFromSpace** [comment]
I made a PR, (and a few mistakes, as seen above) to fix this.

**Comment by CubeFromSpace** [comment]
@explodi, please review and merge my PR

**Comment by explodi** [comment]
Hi, the transactions in future versions will use a different API, so in order to merge this PR i need the new API working. 

You can see how this is being made on the last commits (56d0a81828c834f49999617c636f8079f95ed400, 1d3686e2d5c8d5a785f443669abe7ad1beb80471)

To clarify, this PR *will* be, merged but in a commit using a the new API.

**Comment by CubeFromSpace** [comment]
Ok, but additionally, would I have to change something because of the conversion to Xapo?

**Comment by explodi** [comment]
We'll be using Xapo for cash outs. All other transactions will happen on an internal ledger. I am making a beta test for this new development. You can check the progress of the beta builds here:

http://beta.bitquest.co:8080/job/bitquest/

Will attempt merge this PR now.

**Comment by explodi** [comment]
Just realized this is not a PR but an issue. Nevermind

**Comment by explodi** [comment]
In the new off-chain builds, a 200 bit minimum is not needed (cause there's no fees!) but there *will* be a minimum in cashouts (/transaction) 

I think it's gonna be 1000 or 10000. If it's a e-mail payout via xapo it will be free, but on-chain blockcypher transactions will cost the user a feedetermined by the Bitcoin market. This is subject to change as the beta builds are tested.

**Comment by CubeFromSpace** [comment]
Wonderful! So Xapo API has free transfers?

**Comment by explodi** [comment]
I'm not sure how it works fee wise, I just implemented the API found on http://developers.xapo.com. I chose xapo because its a very respectable company in security of Bitcoins, but we had implemented their API version 1. This is the implementation for version 2.

**Comment by CubeFromSpace** [comment]
I feel like we should make a deadline and/or checklist for BQ 3
