### ISSUE TITLE
Suggestion. Use username for transactions

### ISSUE THREAD

**Issue by juanj** [bitquest/bitquest#115]
What you guys think about being able to use the /transfer command with a username?

For example `/transfer 200 explodi` .
Then the plugin search for the uuid of 'explodi' and then search the address in the DB.
This will make transactions between players easier

**Comment by Burntuno** [comment]
It is already like that and many users do it.

**Comment by Burntuno** [comment]
But we do need 200 bits hard coded into transfers, with some kind of warning when they use less.

**Comment by juanj** [comment]
Oh, my bad xD. What happens with the lower than 200 bits transactions?
