### ISSUE TITLE
Limit number of transactions (for day?)

### ISSUE THREAD

**Issue by juanj** [bitquest/bitquest#117]
We need to add some kind of limit to the transactions, so the players can not spam the wallet.

**Comment by CubeFromSpace** [comment]
I thought there was one already, but I could be wrong

**Comment by theraccoonbear** [comment]
If we build fees into every transaction and make the sender pay them, all of these problems go away.

**Comment by CubeFromSpace** [comment]
That is what seems to be the biggest problem. We just need to make miner fees player funded.

**Comment by juanj** [comment]
This is no longer an issue
