### ISSUE TITLE
Enable "clans"

### ISSUE THREAD

**Issue by medievilminer** [bitquest/bitquest#119]
Would be good if a select group of players could mine the same land claim, pehaps using an invite buy origonal claim holder placing additional sign on the claim that allows another player use the claim?

eg..
^add/ player1^

Would be good for team builds and of course would be nice to be able to remove the access too.

eg. ^/piss off player1^

:)

**Comment by Tracker6310** [comment]
This is a repeat of #67 , it's already been looked at and the code is in a pull request for review/testing

**Comment by theraccoonbear** [comment]
@Tracker6310 #67 has been closed, so it might be worth having an open ticket if this is still something that needs to be done.

**Comment by CubeFromSpace** [comment]
There is no PVP on bitquest.

**Comment by theraccoonbear** [comment]
@CubeFromSpace this pertains to land ownership, not PVP.

**Comment by CubeFromSpace** [comment]
Ok, there is actually a pull request for this, similarly named.

**Comment by CubeFromSpace** [comment]
I think there is a /clan command, but I could be wrong. Someone should test that.

**Comment by CubeFromSpace** [comment]
I think there is a /clan command, I never tried it, but maybe it is meant for team land ownership

**Comment by CubeFromSpace** [comment]
Earlier, I tried it, it said "Internal error" or something like that, so it's not ready yet.

**Comment by explodi** [comment]
@CubeFromSpace did you try on beta.bitquest.co ? It's not on release yet

**Comment by CubeFromSpace** [comment]
Beta.bitquest.co is showing the "session was forcibly closed by remote host" error.

**Comment by explodi** [comment]
I was able to connect to beta.bitquest.co and create the "ewoks" clan

**Comment by CubeFromSpace** [comment]
Not me, maybe it's my client.

**Comment by CubeFromSpace** [comment]
Earlier (before this series of crashing and unhappiness,) I tried it on the beta. It also showed an internal error.

**Comment by juanj** [comment]
That internal errors happened because of the use of the `/clan` command with incorrect number of arguments. This is solved in # 130
