### ISSUE TITLE
I cant join the server

### ISSUE THREAD

**Issue by pURPLESON** [bitquest/bitquest#124]
Hi i cant join the server i have used the ip play.bitquest.co but it says cant connect to the server what is the problem??

**Comment by CubeFromSpace** [comment]
Don't make an issue for this. The server crashed a couple days ago

**Comment by CubeFromSpace** [comment]
It takes a week to fix because the reason is usually corrupted data

**Comment by pURPLESON** [comment]
i never been on it and i will close this issue after you reply ok

**Comment by CubeFromSpace** [comment]
Sure. (Also, im sorry, that was kind of rude.)

**Comment by CubeFromSpace** [comment]
Seriously, the issue needs closed. The server is back up.

**Comment by pURPLESON** [comment]
how

**Comment by CubeFromSpace** [comment]
Ok, no longer up, but EXPECT DOWNTIME!! The server is not completely stable! We don't. Need an issue!
