### ISSUE TITLE
What if we revive emeralds?

### ISSUE THREAD

**Issue by CubeFromSpace** [bitquest/bitquest#125]
Emeralds apparently used to be bits back then, and I (along with @burntuno) thinks that it is a good idea. I have another unique idea, that mob loots are a random amount of emeralds (I'm thinking maybe this:
Emeralds = level * random number between 1 and 32 / 10 + 1. And maybe bonus emeralds for level 50 zombies which are VERY ANNOYING.)

**Comment by CubeFromSpace** [comment]
A couple things we could do is lower emerald costs, as it is 32 emerald blocks (288 emeralds) for 350. The value of an emerald is ~0.8 bits. If the price is lowered to 300, an emerald is then worth 0.96 bits. (Of course, This would need to be approved by @explodi)

**Comment by CubeFromSpace** [comment]
And... nobody responds. (Disappointing...)

**Comment by theraccoonbear** [comment]
And what would a player do with an emerald once they have it (purchased from villagers or found in the wild)?  If you're suggesting that people be able to exchange their emeralds for bits (e.g. actual Bitcoin) then we're back into one of your ideas that requires an endless supply of Bitcoin, and I have yet to hear a plausible explanation for where those would come from.

**Comment by CubeFromSpace** [comment]
This used to happen in Bitquest 1. But if you want me to close the issue, then fine.

**Comment by theraccoonbear** [comment]
I don't have the ability to close the issue, nor would I, but there are continually suggestions that overlook the fact that Bitcoin is not free, so if it's being given to players we need to know where that's coming from.

@CubeFromSpace: Where would the bits given to the players in exchange for emeralds come from?

If you can answer that, I think the idea is fine.  If not, we do not have a balanced/sustainable economy in the game and it will indefinitely require external funding sources (e.g. from charitable players) which is not going to last over time.

**Comment by CubeFromSpace** [comment]
Apparently, you not only exchanged them for BTC, but you also could buy them. I would say that maybe the BTC to buy them could be used for selling them. Additionally, we could possibly make the sell price lower than the buy price, so you would need more emeralds to get the same value. Unless you say that makes no sense, which is fine. I will gladly pay a few thousand bits if it's necessary, unless none of what I'm saying makes any sense at all. I also meant that if you told me to, I would close the issue. (Also, tell how any of this would negatively affect the server)

**Comment by Xeyler** [comment]
The problem with allowing emeralds to represent bits is security.

In classic BitQuest, when bits were transferred into the game, all bits were tossed into one wallet. When emeralds, representing bits, were withdrawn, they were transfered from BitQuest's single wallet.

What happens if there's a glitch that creates more emeralds? What happens when more emeralds are found in the world than there are bits in BitQuest's wallet? It's not unlikely that, at some point, someone would try to withdraw too much. In this case, BitQuest is literally bankrupt. I'm not sure, but I suspect that this may have happened a couple times(That's a question for @explodi ).

We switched to individual accounts for players for security. Of course, if you have a solution to this problem, that would mean trading bits between players without fees or waiting for confirmations. 

Switching back to emeralds would involve big advantages and severe risks.

**Comment by CubeFromSpace** [comment]
What if emeralds couldn't be found naturally? Maybe that would reduce the chance of bankruptcy, along with a daily maximum...?

**Comment by CubeFromSpace** [comment]
Never mind. Just tell me, is this the stupidest idea you've heard? If so, I'll just close this issue

**Comment by theraccoonbear** [comment]
I don't think this is a stupid idea per se, but I think the details of how it would work really need to be ironed out.

**Comment by CubeFromSpace** [comment]
It's just that my idea was crushed, like all my other ones. I really just want to help the server.

**Comment by Xeyler** [comment]
Personally, I was sad to see the emerald system go. I think if there were a good way to implement it again, I'd support it.

The biggest problem is that the idea isn't completely fleshed out and thought through. We're just laying out the pros and cons, we're not putting down the idea. It's all just part of the process. If you're hoping for more productive results, I'd recommend adding a bit more detail to your posts and comments. If you give us more material to work with, we can get to a better place with the idea quicker.

Of course, don't do the opposite by adding so much it's unorganized and hard to read(I've been guilty of that several times).

**Comment by CubeFromSpace** [comment]
I'm sorry, my comments aren't very organized. I might need to think of a way to make emeralds induplicable.

Maybe, if emerald ore is taken out of the world, and prohibited to mine or place. That might reduce duplication. 
Another thing, if Some infinite source of BTC was possible, maybe it would be easier to manage.

**Comment by theraccoonbear** [comment]
I think a lot of these not-yet-fleshed-out concepts might be better workshopped in Slack than here on GitHub, honestly.  The ideas themselves are fine, but I don't think a GitHub repo's issues section is really the right place for spitballing at this level.

**Comment by CubeFromSpace** [comment]
Ok, except explodi never really responds to me, and I literally can't figure out how to do a PR anyway.

**Comment by theraccoonbear** [comment]
I suspect explodi is fairly busy.  I have gotten responses from him when I directly message on Slack, but it often takes a while.

To do a PR you will need to fork the official BitQuest repo, make your changes, commit/push them to your fork of the repo, and then create a pull request from the new changes (your feature or master branch) on your repo, to master on the official BitQuest repo.  I don't see any repos in your account right now, so forking would be a good place to start.  Once you've forked, you can check your repo out to do development.  If you're not familiar with that process, I would start by brushing up on git and GitHub.

**Comment by CubeFromSpace** [comment]
Ok, thank you. I can also fix a few other issues.

**Comment by juanj** [comment]
The current system has also a security flaw. The private keys of the server and all the players are stored on the DB. This is bad in two ways.
1. Players are not in control of their funds. For example, when BitQuest is down, all funds are locked in.
2. If BitQuest server get compromised, all funds (server and players) are lost.

A solution to protect player funds will be to not have player wallets on the server. Each player would have to have their own wallet. If a player wants to pay to the server, then the server generates a unique address for that payment. This of course will carry the fees and delay problems.

One alternative to the actual system that still have that security flaw, will be to have one main wallet on BitQuest and save user balances in the DB. Doing this will allow internal instant transactions without fees. Is kinda like the emeralds system but removing the security issues of Minecraft. This, as well as the current system, destroys the filosofy of decentralized Bitcoin.

**Comment by theraccoonbear** [comment]
This is how the vast majority of online exchanges (e.g. Coinbase) work: they warehouse the wallet, specifically the private key required for making payments.  IMO, anyone putting more money into, or just generally storing more money in, a BitQuest wallet than they're willing to lose (either permanently or access temporarily) is being foolish.  I think the complexity and overhead to doing transactions out-of-game would be more pain then it's worth, but that's just my $0.02

Tracking user balances in-game via a single Bitcoin wallet and in-game ledger (in REDIS, or whatever) is, as I understand it, how BQ1 operated: instant transactions, no fees, etc.  It also, as you mentions, does not in any way alleviate the security concerns, it just facilitates faster/cheaper game transactions, albeit off-chain.  Whether that's desirable or not probably depends on whether BitQuest's objective is:

1. To provide a unique Minecraft experience involving a currency, as an abstract concept, or...
1. To genuinely explore the feasibility and practicality of using Bitcoin on-chain for micro-payments

The actual objective is probably somewhere in the middle, but I am inclined to lean more towards the second option, personally.

**Comment by CubeFromSpace** [comment]
One problem: @explodi doesn't seem to be responding to anyone, and he hasn't reopened BQ, it's been at least a week, and he's even visited slack without saying anything.

**Comment by juanj** [comment]
@theraccoonbear I was thinking on a good solution to this and found about Lightning Network. It kinda solve this problems, but, as far as I can find, is not quite ready yet. Also @explodi said something about using sidechains and payment channels. I don't know if he has any progress on this.

@CubeFromSpace I know how you feel, but @explodi (like all of us) has other things he has to do apart of BitQuest. Also if you can see he has done some commits (28ac9ed and 4b9c175) so I think he is trying to fix the crashes.

**Comment by CubeFromSpace** [comment]
Eh... you're right. He does come online though.

**Comment by CubeFromSpace** [comment]
I wonder... what if 1 emerald = 1 satoshi instead?

**Comment by explodi** [comment]
If the problem we are trying to solve is the increasing miners' fee and microtransactions in the blockchain not viable anymore, Emeralds can be a tricky solution if a Minecraft bug or memory leak imposes a rollback of the world or a player inventory is lost.

I am proposing a solution (in the "offchain_payments" branch) to the problem by opening up an internal credit ledger in the server's database. That means transactions for purchases, loot and land claims will be recorded as "payment balance" in a database number, and settled when cashing out. So miner fees will only be necessary when using /transfer to an outside address.

**Comment by Xeyler** [comment]
Trading in-game won't result in a backed up wallet, and there won't be fees unless they're transferred to an external wallet.

On the other hand, security will have to be tight. I think you're up to that task, though.

Sounds like a good trade off.

**Comment by jadiesel** [comment]
Might be a good idea to have a built-in delay before funds are available to withdraw... just in case. Not that anyone would purposefully try to get rich 1000 bits at a time though, right?

How about the user pays the miner fee when xferring out of the game? Or you charge them a higher fee, and the game keeps a small bit.

**Comment by CubeFromSpace** [comment]
I think this needs it's own issue, and I think it already does.
I'm going to close this comment because this idea needs some thought
