### ISSUE TITLE
Player can re-join when kicked from clan

### ISSUE THREAD

**Issue by Tracker6310** [bitquest/bitquest#126]
When a player accepts invite to join a clan, invite is not deleted. 
If player is kicked from clan at some point, invite is still in redis, allowing them to rejoin at any time

**Comment by CubeFromSpace** [comment]
Wait... clans are working?

**Comment by theraccoonbear** [comment]
@CubeFromSpace I've not been on for some time, but I believe clans have been in place on beta for some time.  I've seen it discussed on Slack.

**Comment by CubeFromSpace** [comment]
Isn't there a way to delete the REDIS info from the plugin? Maybe that will help

**Comment by juanj** [comment]
This issue can be close.
The problem is fixed in #130

**Comment by CubeFromSpace** [comment]
@explodi /\
                 |

**Comment by CubeFromSpace** [comment]
Oops
