### ISSUE TITLE
Villagers sell nothingness

### ISSUE THREAD

**Issue by CubeFromSpace** [bitquest/bitquest#135]
Not too long ago, (Before the end of the longest active streak I've ever seen XD) I tried to buy 8 sponges, but my inventory was full. Therefore, it completely canceled the 8 sponges and still took my 200 bits. (keep them :P) that may cause major problems once the trendiness of BitQuest comes back up (Which I hope happens)

**Comment by CubeFromSpace** [comment]
In the Bukkit API, is there something like `player.invFull`?

**Comment by theraccoonbear** [comment]
I fixed this exact issue in #77 but saw that it was rolled back at some point.  No idea if there were issues with the code or a poorly resolved merge conflict, but this bug was fixed at one point.

**Comment by theraccoonbear** [comment]
Actually it looks like the discrete (and thus useful) error messages were removed by the logic's still there.  If it's not working now, I'm not sure why or what's changed, but I haven't touched the code or played in quite some time.

https://github.com/theraccoonbear/bitquest/blob/master/src/main/java/com/bitquest/bitquest/InventoryEvents.java#L126

**Comment by theraccoonbear** [comment]
My only thought would be if the wet/dry sponges are the same item type in inventory but have some flag  for their wet/dry state internally.  That might account for a logic error and perhaps a better "can stack" check is needed beyond what's done currently in the `hasOpenSlots` determination.  I don't have time to dig into it currently, but if anyone else does, that might be where I'd start.

@CubeFromSpace did you have any sponges, wet or dry, in your inventory at the time, and if so, how many of each?

**Comment by CubeFromSpace** [comment]
@theraccoonbear No, I had no sponges, wet or dry.

**Comment by CubeFromSpace** [comment]
@explodi, any thoughts on this?

**Comment by CubeFromSpace** [comment]
I think this was fixed
