### ISSUE TITLE
Need Clan tags, a clan list, and way to delete old, non used, clan names.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#139]
Need a way to show show clan tags when player presses TAB.

Would be great to have a /clan list function to list clans and memebers.

Maybe a way for Moderator to clear out non used clan name or however.

**Comment by CubeFromSpace** [comment]
Clan tags upon TAB is done. I dont know about the other ones

**Comment by Xeyler** [comment]
Clans that have no members should automatically be removed.

This would be checked each time a player left a clan until the last player left.
