### ISSUE TITLE
Teleport idea...

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#140]
I was thinking it would be nice and could help fund server, if we had a pay to initiate multiple teleport system.  Idea is, stand in place you would like to have a teleport to, use a command like '/tps add CustomName', server charges 1000 bits to unlock that location, user can teleport to that location anytime with a command like '/tps go CustomName', and they can make as many locations as needed, each costing 1000 bits to initialize.  Other commands could be, '/tps list' to show all player's teleport locations and coordinates and maybe '/tps random CustomName' which charges 1000 bits and sends player out to a random location within like 20,000 or 60,000 blocks, unlocking that as future teleport.  I was thinking /tps should be used to not conflict with /tp.  I think regular players would use this multiple times for different towns or personal areas.  Also, maybe each player can have 1 free teleport location, the 1st one they choose to make.  Hope this makes sense and can be good for BQ.

**Comment by CubeFromSpace** [comment]
@burntuno, @explodi, we've been debating this on Slack, and I think we first need to remake the loot system and also make an ingame transaction system.

Otherwise, I think we also need compass TP tax, maybe 5 or 10 bits per.

@theraccoonbear, I know you probably need to tell me the flaws of it. (It's a good thing sometimes, it needs opinion)

**Comment by Burntuno** [comment]
I think compass and bed should be free and no Bits per Teleport.  One time initiation fee to setup an unlimited TPS location, is what I mean.  So what happens when you TP and you die ASAP... then you feel robbed.  Lag and disconnect could be an issue too.  That is why I'm not fan of payment each teleport.  I think we should give the players open ability to make many and anywhere TPS locations, just each one costing like 1000 bits which goes directly to server, not loot.

**Comment by theraccoonbear** [comment]
I agree with @Burntuno that compass/bed should be free.  Bed must be free, or what happens when a player dies and has no bits?

I think setting a TP location should have an initial cost and then usage cost.  Maybe something like 500-1000 bits to _create_ a TP destination and then maybe something like 10-50 bits per _use_?  Building it with ongoing, usage based fees could help sustain the fee wallet and/or loot.

**Comment by syrianrue** [comment]
i dont think the per use should grow over time. but if it grows over time then after paying the relatively high creation fee, they are they discouraged from using it as continual use is taxed at an ever increasing rate. make the initial or per use higher instead.

**Comment by theraccoonbear** [comment]
@syrianrue I never suggested the cost grow with use, I'm saying I don't know a good price point and am providing some proposed ranges.  The important thing is that it be recurring.  These one-and-done sales are not going to sustain BQ's economy.

**Comment by syrianrue** [comment]
ok, i guess i was confused by your statement "Building it with ongoing, usage based fees" because it sounds like the fee is building. but yeah having a creation and per use fee makes sense.

**Comment by Burntuno** [comment]
I think since you could buy many TPS, each costing 1000 bits(at least) , it isn't really a one and done.  Our regular players are already all over map and would buy more as new areas open up.  New players come and go on BQ.  Some play hard for a month and are never seen again.  If each of these buys 1 or 2 TPS, before they stop playing, it could generate bits for server not loot.  In other words, I just don't think it should be per use, even if it has to cost more for creating TPS point.  Either way, now I can travel almost anywhere in combination of Nether Road and Elytra Tower within a few minuets.  We may never really need this feature.  Travel is [Bit]Questing after all.

**Comment by theraccoonbear** [comment]
Personally, riding AFK in a mine cart to travel 10s of kilometers doesn't really constitute "questing" or even gaming, in my mind.  It's an annoyance, and as a result, isn't something I will do.  I think teleports would be very useful, and a reasonable generator of money (to fund whatever) but I think having a nominal per use fee is important beyond just setting up the TP.  That's my $0.02

**Comment by CubeFromSpace** [comment]
I guess you're right now that even 2 bits becomes excruciatingly hard

**Comment by Xeyler** [comment]
This was addressed in my plans for the compass.

Players would be able to teleport to each of their claims. Of course, that could get hard to navigate if you have a lot of claims, but you'd be able to sort them by most commonly teleported to, location, etc... On top of that, they'd be able to separately teleport to moderator-defined spots(similar to how it worked in Classic BitQuest).

Here's a presentation for anyone interested: [Compass Plans](https://vimeo.com/178386781) (You can see that is has much more than just teleporting as well)

**Comment by theraccoonbear** [comment]
@Xeyler I'm not hearing any audio on that video, so it's tough to know what's going on.  Am I missing something?

Having options to teleport to any of your claims might be cluttered for folks like me who have 30+ plots all adjacent to each other.  I only need to get to that area, not each 16x16 chunk.

**Comment by Xeyler** [comment]
Sorry about the audio, it was cut off when I exported for some reason...

But I do plan to address the adjacent plots issue. You'd be able to filter the plots to represent many adjacent plots as one.

**Comment by Shiny-andKittens** [comment]
And this may work due to the 1000b fee
