### ISSUE TITLE
cartographer maps

### ISSUE THREAD

**Issue by syrianrue** [bitquest/bitquest#141]
just had an idea for something that might sell well in the villager store; cartographer maps. its normally only available as a villager trade, so now they are impossible to get. not such a big deal for ocean monuments because they are common enough, but woodland mansions are very hard to find. plus the maps actually look pretty cool on a wall.

**Comment by CubeFromSpace** [comment]
This server was created LOOONG before that, and those maps may not work. Reason: only unexplored chunks can have them, and most chunks have been explored until around 30000 blocks away.

**Comment by CubeFromSpace** [comment]
My point: all villagers are within 2000-4000 blocks of 0, 0

**Comment by syrianrue** [comment]
well im not the only user whos been out past 50k where new chuncks with villages and woodland mansions form... 

but then again, maybe its just easier to sell totems of undying, albeit less fun to acquire them than if you have to travel far and make a journey out of it.

**Comment by CubeFromSpace** [comment]
If you want to spend the money on it, I'll add it to my PR #138. (PR for villager items)

**Comment by CubeFromSpace** [comment]
@syriansue There is no Bukkit value for that. It has to be under MAP, but I haven't figured out how to do NBT data yet. @explodi pls halp

**Comment by syrianrue** [comment]
yeah ill definitely buy one. i guess ill just have to travel far out, otherwise the map will say the nearest mansion is 20, 30, 40k in some general direction. it will be easier to be nearer to those new chuncks to start with. and if theres ever a market for totems, i think a lot more people will be buying those maps too.

**Comment by syrianrue** [comment]
yeah i guess there has to be some way to hook into the original villager function of generating a new map. i havnt messed with bukkit before so idk how to do that.

**Comment by juanj** [comment]
I did some research on this and there is no way to hook the original treasure map generation code.
To do something like this we will need a way get the location of the structures and place them in the map. Then create a custom render for that map.
