### ISSUE TITLE
self-regulating loot dispensing

### ISSUE THREAD

**Issue by theraccoonbear** [bitquest/bitquest#143]
Regarding @explodi's issue https://github.com/bitquest/bitquest/pull/142#issuecomment-290584987

It would be great to create a loot reward system that automatically adjusts itself to dispense more loot when more bits are paid into the loot wallet.  Using some sort of moving window average (think: how BTC mining difficulty auto-adjusts periodically)

**Comment by CubeFromSpace** [comment]
Is there a way to read the amount of bits in the main wallet?

If so, I was going to make a PR for random stuff.
