### ISSUE TITLE
Villagers will steal items without buying them.

### ISSUE THREAD

**Issue by Xeyler** [bitquest/bitquest#146]
In [InventoryEvents](https://github.com/bitquest/bitquest/blob/df9ac790a180a815ea5b6ac339079bbdcbc71537/src/main/java/com/bitquest/bitquest/InventoryEvents.java#L214), when a player sells an item, the item is taken from their inventory, then BitQuest tries to make the payment. It should instead pay first and then take the item in case their aren't enough bits in BitQuest's wallet to pay.

Also, the player should be given an error message if the payment doesn't go through(returning false).

@explodi, you should be the one to verify this issue and make a fixing commit. I don't dare change things that involve payments this much.

**Comment by CubeFromSpace** [comment]
I think it should be disabled until its ready, because it is basically giving away money

**Comment by CubeFromSpace** [comment]
Nvm, expiremented, the problem is you need some decent donations.

**Comment by Xeyler** [comment]
Fixed by commit: d355952e384146512bf02d4b5041c9ba2ff4ce82
