### ISSUE TITLE
Claim command doesn't support spaces in claim names

### ISSUE THREAD

**Issue by Xeyler** [bitquest/bitquest#149]
When using commands to claim land, arguments are separated by spaces.

Presumably, the code uses just one argument instead of concatenating it with all arguments following it.

I will investigate further later.

**Comment by CubeFromSpace** [comment]
How about trying something like if args [<1] = (alphanumeric characters)

Or if there's a way to select multiple arguments

**Comment by Xeyler** [comment]
I created a commit that concatenates the arguments, but that's an incomplete solution.

In concatenating the arguments, we can only assume that there was just one space between args. PlayerCommandPreprocessEvent is the only way we can access unfiltered command to know exactly where spaces are, so we should consider using that instead.
