### ISSUE TITLE
Ban Command Doesn't Work

### ISSUE THREAD

**Issue by Xeyler** [bitquest/bitquest#150]
I suspect issues with how UUIDs are set and read between the [Player Join Event](https://github.com/bitquest/bitquest/blob/master/src/main/java/com/bitquest/bitquest/EntityEvents.java#L87) and the [Ban Command](https://github.com/bitquest/bitquest/blob/master/src/main/java/com/bitquest/bitquest/BitQuest.java#L1096).

**Comment by CubeFromSpace** [comment]
And maybe while this is fixed, you could add a feature to transfer his/her balance to the loot wallet when banned too.

**Comment by CubeFromSpace** [comment]
@xeyler @explodi I found a typo:
               if(BitQuest.REDIS.sismember
                                              /\
(Sorry, on smartphone or I would be able to say which line)

**Comment by CubeFromSpace** [comment]
Wait, maybe that wasn't a typo. (Very sorry)

**Comment by CubeFromSpace** [comment]
@Xeyler @explodi What if we make a fallback command to add players to the Serverside banlist rather than to our REDIS database.

**Comment by Shiny-andKittens** [comment]
@xeyler Juanj has fixed this.

**Comment by juanj** [comment]
This issue can be closed.

**Comment by Shiny-andKittens** [comment]
@explodi

_I have flagged this issue for demolition_
