### ISSUE TITLE
Claim Transfers not working with sign when playernames are long.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#156]
In early BQ2.0 using signs, plot names could be very long and have symbols in them.  This feature is missed and now plot names are shortened to 16 max.  Being max 16 letters is also messing with sign transfers.  Doing the ^transfer Playername^ won't work if total letters including transfer is over 16, so players with long names can't receive a plot transfer.  If there was a way to have full sign length names back, it might resolve this issue.  Also, I can never get /land transfer PlayerName to work.  So I've always used signs.

**Comment by DabTime** [comment]
This will also not work if the player has a symbol in their name. I tried to transfer to 8_Mile today and it did not go through because of the underscore.
