### ISSUE TITLE
Curse of Binding Pumpkin Issue

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#157]
A player received from another, a Curse of Binding Pumpkin, which now can not be taken off and since we have keep inventory on, it is stuck.  Armor pieces would eventually break off, but a pumpkin has no damage to break.  Might be best to remove the affects of this enchant for our server.  Now an Admin or new way is needed to help this player out.

**Comment by CubeFromSpace** [comment]
Is there a way to detect enchants on certain items? (Sorry, I'm still not good at Bukkit, but I'm reading JavaDocs). If so, you can remove a pumpkin with the enchant.

**Comment by AndrewBuck** [comment]
The ItemStack class has a getItemMeta() function which returns an [ItemMeta](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/ItemMeta.html) type.  I think this will let you do what you want.

**Comment by CubeFromSpace** [comment]
Great! (Although now I would need to read more JavaDocs to do that, so, by the power of the internet, I shall summon @explodi to this issue)

**Comment by Shiny-andKittens** [comment]
@explodi magical internet summon pls

**Comment by Shiny-andKittens** [comment]
By the power of the interwebz, @xeyler, I summon thee!

**Comment by Shiny-andKittens** [comment]
@explodi or @xeyler please answer

**Comment by juanj** [comment]
Drink a bottle of water and all the pain will go away!
(Needs #180 to be true)

**Comment by juanj** [comment]
(Now that #180 is merged this issue can be closed)
