### ISSUE TITLE
/ignore chat feature

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#158]
Need this enabled so some players can ignore others for various reasons.  Let it also ignore Moderators since sometimes their chats can be redundant, which helps others listening, but regulars know it already.  Let whispers make it through the /ignore so Moderators, or whoever, could get message threw if needed.

**Comment by syrianrue** [comment]
i agree with all of that. my only suggestion is not to hobble /ignore by allowing PMs to get through as you can imagine the scenario of a user like crazyminer setting up PM spam script. but allowing Mods to get through the ignore in PMs would be good since they might have important messages.

**Comment by Burntuno** [comment]
However it works out, I think /ignore for Moderators is fine, because of our redundant shouts helping new players.  Ability for Moderator to whisper through a /ignore, would be key to this.  Saying this, makes me think, maybe Moderators need a /announce command that puts up a Bright or highlighted chat line of important information, for all players.  Example would be "/announce Server reload expected within next 5 mins." or "/announce Server maybe offline tomorrow for maintenance."

**Comment by CubeFromSpace** [comment]
I think we should also make a /mute command to shut up CwazyMiner.
