### ISSUE TITLE
Players who have not play BitQuest in a long time come back to a bug.

### ISSUE THREAD

**Issue by Burntuno** [bitquest/bitquest#159]
Observing that old Bitquest players from prior versions of Minecraft(1.9, 1.10, 1.11), not sure which, return to game with a few bugs.  Missing Bitquest Balance: ## on right of screen, compass not teleporting to spawn, and ability to access claimed plot chests, are part of the known bugs.  This bug resolves itself after some time of playing or by next day, it seems.  Security issue is they can access Moderator chests in Satoshi or chests on other players plots.  Once Scoreboard comes back and compass works, it seems all is fine.

**Comment by Burntuno** [comment]
This bug has shown more symptoms.  Now when server full and busy with new players, same bug occurs.  The player is missing scoreboard, compass not working, and they can access protected chests.

Is it possible the Wallet API limit is reached and the players data is not fully initialized with server?  If this is the case, would it be possible to put player in a Spectate or Non affecting mode while on the wait list for data to complete?

Another place to look for bug could be Unique chest protections.  If player renames chest with 'public' in name, they can let all access.  Maybe these new bugged player's games think all chests are 'public' until their data is initialized?

**Comment by Shiny-andKittens** [comment]
This does not help now that Fuze III fans come online all the time

**Comment by explodi** [comment]
This was fixed a while ago, there was an API limit on HD wallet creation and now the server will kick users when said limit is hit. They are presented with the message "Can't join right now. Come back later".

Please don't hesitate to reopen this issue if it happens again.
