### ISSUE TITLE
Updated images for README.md

### ISSUE THREAD

**Issue by Shiny-andKittens** [bitquest/bitquest#166]
The first image is an early concept of loot, the second a screenshot of BQ 2.0 transfers. (We are in 2.1)

**Comment by juanj** [comment]
Also this statement is no longer true.

> Thanks to the open nature of Bitcoin, all transactions in the server can be seen on the Blockchain using tools like Insight or Blockchain.Info. This is helpful for debugging and transparency.

**Comment by theraccoonbear** [comment]
@juanj is the new hybrid on/off-chain transfer/payment system documented anywhere?

**Comment by Shiny-andKittens** [comment]
@theraccoonbear not on README.md, I don't think

**Comment by Xeyler** [comment]
@theracoonbear, I've been trying to update the wiki. [This page](https://github.com/bitquest/bitquest/wiki/Your-In-Game-Bitcoin-Wallet) offers some information on the hybrid system.

I haven't gone through the README yet, though. I'll make some changes.

**Comment by Shiny-andKittens** [comment]
@explodi we need the server online to do this

**Comment by explodi** [comment]
Now it's possible to start the server without an HD wallet, or no wallet at all. It needs to be tested more and I can update more documentation.

The idea is that production BitQuest can run in a cold storage with a hot wallet and HD addresses when configured that way, but by default it runs in hot wallet mode, meaning there's nothing to be configured (just your address and private key)
