### ISSUE TITLE
Make effects more random

### ISSUE THREAD

**Issue by Shiny-andKittens** [bitquest/bitquest#178]
I think that the effects are too powerful, so I think maybe we should make more like this:
A random number between 0 and 5 is chosen (because minecraft does that +1, so it is lvl 1-6), and that is the potion strength used.

**Edit: We cannot do anything more than level 4 for Resistance or mobs/players could become invincible.

I also think we should add more possible effects, like maybe haste and night vision, because those may help too.

**Comment by explodi** [comment]
You mean enemy effects?

**Comment by Shiny-andKittens** [comment]
Yes, but that also affects what creepers explode into.

**Comment by Shiny-andKittens** [comment]
@explodi It would further enforce the RPGMMO theme

**Comment by QuentinTy** [comment]
Currently literally more that half of the mobs have absorption and of those half got resistance. its so annoying killing mobs without creeper effects. creeper effects seem impossible now.

**Comment by Shiny-andKittens** [comment]
I'll make another issue regarding that
