### ISSUE TITLE
Use Case: QR Codes Used for Server Revenue

### ISSUE THREAD

**Issue by kordless** [bitquest/bitquest#18]
This is an epic (use case) issue and the output is additional issues which comprise the work that will need to be done to complete it.

*Use case*: Enjoy regular revenue for a given Minecraft server based on the demand for popular land plots. This is enabled by the use of QR code generators which are tied to a server's primary wallet. 

Here's how this will work (combined steps and requirements):
  1. Each server gets a wallet it controls powered by BlockCypher's hosted wallet methods.
  1. Operators/admins may generate gridded overlays for a large areas which are expected to be highly trafficked/populated. Zero, zero, for example.
  1. Players may create grids in remote areas by placing a sign with some specific data on them.
  1. Both the overlays and signs contain information to configure the grid's payment periods, including length of period, minimum period length, etc.
  1. Both the overlays and signs contain information to configure the grid's payout strategy.
  1. Each grid square created, either by admin overlays or player signs, is assigned a Bitcoin address.
  1. Two contrasting colored blocks are reserved for the system and are unbreakable by users. Special colored wool, for example.
  1. QR codes are generated and built using algorithms and placed within the grid square's boundaries, which correspond to the Bitcoin address assigned to the grid. The code for this already exists.
  1. QR codes are built into "clouds" for aesthetics and are positioned at a set altitude. The code's plane is horizontal and parallel to the normalized ground plane.  A player would "look up" to see the QR code on his screen.
  1. Viewing platforms may be created by users or admins where necessary for accessibility.
  1. Payment to addresses are made by players using standard Bitcoin wallets on their phones. 
  1. Users interact with QR codes by pointing phones at the screen, make a payment to the code's address, and see a notification in chat as a result of payment.
  1. Players "register" a payment address (wallet) to their account by going to a website and entering their username and making a small payment (perhaps this becomes the signup flow).
  1. Payments to a given grid square's by a player using their payment address (wallet) allow the user to build for X amount of time in that region.
  1. Players who are currently able to build in a region will receive a percentage of payments by other users wanting to build in that same region.
  1. As a region becomes more popular, receiving more payments over time, the "price basis" for building in that region can go up, and become prohibitively expensive to players who have never built in that area.
  1. If a user wants permanent rights to build in a region, perhaps even reserving it for their home, they set up recurring payments using Coinbase or Stripe.

The net benefits of this use case is multi-fold:
  1. The server's existence becomes tied to it's populartiy. If the server is popular, it make more money. The more money it makes, the more likely the admins will continue to run it, and run it well.
  1. Auditing user behavior becomes trivial. Users must make payments to build in a given region. Those payments should be made public through an in-game lookup tool (something like /grid payment list).
  1. The home ownership concept becomes trivial to implement. If you want a home somewhere and don't want it griefed much, you pay a relatively large amount to the local grid address and set the minimum build period to a month. Relative is relative, of course. If you can only afford $1/month for the grid, and someone finds $1 worth griefing your home, so be it. At least you get some money back when they do it.
  1. Public works become an organized, federated effort, and can be rewarded using payments. Moderate sized, recurring payments can be made to regions containing rails, canals, highways, inns, and the like to both encourage improvement of the works and minimize griefing. While regions will be quite large in area/dimension, moderate sized payments along the public works paths will prevent most users from wanting to take the time to grief the area.

Here are a few sub use-cases for this (using US$ for comparison):

Spawn become *interesting*. Anyone can technically build at spawn, but to do so will cost you. Let's say 20 users decide they want to build a kick ass town. They all dump $5/each into spawn's address around the same time. The cost basis for spawn, assuming it's set to a month, immediately becomes $100/month. That means anyone wanting to build in spawn for a month's time, at that point in time, will have to pay $100. If they want to build in spawn for a day, and spawn's grid allows that as a minimum period, it will cost them $3.33/day.

Remember, the existing spawn builders (those 20 users who paid $5 each) can get a cut of the new revenue, so it may be worth it to them to allow for shorter minimum build periods.

Home ownership plots become trivial to implement. The existing place your bed system sucks, for a variety of reasons, including placement, code implementation costs, etc. By finding a nice location, and even sharing it with some neighbors, an equilibrium can be reached that is comparable to today's real life neighborhoods.  If your neighbor steals your stuff, then you know that whoever stole it has permissions to build in your home's grid. You can look to see who made payments to the grid recently and then report the event to the admins or community, if it warrants it. 

Large complex neighborhoods, or even apartment buildings become worth working on, because anyone wanting to live in an apartment building will pay to live there, which then pays out to all the people currently living there, making it worth a community effort to keep the building in good repair.

Older abandoned builds become "claimable" and can be torn down if needed.

**Comment by Xeyler** [comment]
This certainly is an interesting idea, and maybe some of the things mentioned could be implemented over time, but, for now, it's a little too complex. We don't want the learning curve to be too steep for new players.
