### ISSUE TITLE
Reduce the distance-based nerfing

### ISSUE THREAD

**Issue by Shiny-andKittens** [bitquest/bitquest#184]
@explodi doing spawndistance / 2048 is too much and we no longer get any powers other than resistance and absorption. Try to make it at least spawndistance / 1536 (75% as much) and raise the chance for effects _slightly_.

**Comment by QuentinTy** [comment]
what determines spawn distance? 0,X,0 or at a active used bed? If its 0,X,0 then creeper effects have been mostly broken (or patched because its just a bug)

**Comment by Shiny-andKittens** [comment]
@QuentinTy it's determining how far from spawn, it would break into absolute destruction if it was Bedspawns. The Overworld mobs are too weak to give good effects easily. Neither are they too hard to pose a major threat.

**Comment by QuentinTy** [comment]
Ok, i was 50k out south and mobs weren't that high level... rip creeper effects unless mob level cap is raised or effects become the old random system.

**Comment by Shiny-andKittens** [comment]
I think the cap should be raised, although I have found creepers bearing every effect except strength.
