### ISSUE TITLE
When a player is banned, his/her balance should be given back to the Loot Wallet

### ISSUE THREAD

**Issue by Shiny-andKittens** [bitquest/bitquest#189]
Otherwise it becomes lost and hard to recover.

**Comment by crankycrypto** [comment]
Why not give the balance to the banned player? It is worth real money and there would be a conflict of interest to ban players just to increase loot.

**Comment by explodi** [comment]
Banned players who request balance can contact the mods and have their balance withdrawn if not stolen. I agree with @crankycrypto on the incentive problem for banning players, and similar drama has happened before.
