### ISSUE TITLE
Levels appear to be lost when repairing or enchanting

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#19]
This is because of a conflict of the vanilla minecraft level system vs. the bitquest level system. Levels actually arent lost but it appears so.

**Comment by Xeyler** [comment]
We should clean up our experience handling... We only need to cancel the player level change event, which we have done already. I'll get on cleaning up a little.

**Comment by SnowyMiner** [comment]
Will clans be added soon?

**Comment by Xeyler** [comment]
Perhaps... I think I'm gonna work on the compass before clans, though... Also, this channel is for bug discussion. Try reddit next time. <3

**Comment by SnowyMiner** [comment]
O_o
