### ISSUE TITLE
Confused about btc origin

### ISSUE THREAD

**Issue by TheHeroBilly** [bitquest/bitquest#194]
I've been considering host a server based on your code for a private group of friends. (Mostly to try make a small profit to cover costs). Where does the btc come from? Is it generated by the server or is it provided by the host and users?

**Comment by syrianrue** [comment]
the btc comes from users that deposited and bought from the villager shop

**Comment by QuentinTy** [comment]
The bitcoin in bitquest is ONLY deposited and recirulated. As the server uses real bitcoin it cannot be generated out of thin air and must be from the main block chain.

**Comment by TheHeroBilly** [comment]
Well I understand how Bitcoin works. I just was unsure if it was being mined as the server was run

**Comment by Shiny-andKittens** [comment]
@TheHeroBilly

Mostly donations from players but Bitquest is in a horrible state and there’s almost no players willing to donate.

That means most of the money comes out of @explodi ’s pocket, which is sad, because he probably has better things to spend it on.
