### ISSUE TITLE
We should try to get some mining services attached to Bitquest

### ISSUE THREAD

**Issue by Shiny-andKittens** [bitquest/bitquest#195]
After that, we would get hourly/daily BTC sent to the wallet and we wouldn’t have to worry about the server running out of BTC or about @explodi having to empty his pockets to fund BQ.

**Comment by syrianrue** [comment]
you want a general purpose server to mine crypto? thats terribly inefficient and would just waste money. someone would need to buy some cloud mining contracts (usually a scan), or buy some asics.

**Comment by MichaelPriebe** [comment]
There's many plugins that let you put advertisements in the server even billboards using maps in-game. I would love to see ads if that would increase our gains and/or help @explodi out.

**Comment by Shiny-andKittens** [comment]
@syriansue I think a service called Genesis-Mining is more legitimate, and @burntuno uses something (can’t recall name) that he says he gets payed for

**Comment by radostin04** [comment]
@MichaelPriebe Here's the thing - @explodi wants as little third-party code running on the server. Currently, the only third-party plugin installed (To my knowledge) is NCP. And also - I don't think @explodi would be too happy advertising thigns in game. Hell, he doesn't even advertise another game that his team is making.

**Comment by syrianrue** [comment]
ok lets use the example of buying from genesis.

https://www.genesis-mining.com/pricing
so lets say we buy a 2,500 gh/s contract for 350$
that will generate a projected Ƀ 0.00001298 /month

heres a link to the bitcoin profitability calculator i used https://www.cryptocompare.com/mining/calculator/btc?HashingPower=2500&HashingUnit=MH%2Fs&PowerConsumption=0&CostPerkWh=0

**Comment by radostin04** [comment]
Doesn't Genesis havesome sort of maintenance fee? And also, that's only 13 bits a month. Not very much.

**Comment by syrianrue** [comment]
yep. thats the point

**Comment by williamronn** [comment]
Don't want to disturb your conversation but if you look at [genesis-mining's](https://www.genesis-mining.com/pricing/) website it shows they are out of stock on bitcoin miners atm :| Just saying that could be a key part of this.

**Comment by fumasa** [comment]
why not use some adjustment of the process Pirate Bay is using? maybe limiting the amount of cpu used and that kind of control?

**Comment by dildosex** [comment]
Ya
