### ISSUE TITLE
best solution for issue #195

### ISSUE THREAD

**Issue by ScienceDemon** [bitquest/bitquest#199]
@explodi , would you be so kind as to email me at sciencegamesmain@gmail.com so i can tell you a plan to fix issue #195 but with the words 'mining services' replaced with 'miners'?

**Comment by theraccoonbear** [comment]
@ScienceDemon why don't you just post your proposal here?

**Comment by syrianrue** [comment]
theres no "fix". issue #195 was one persons idea for someone else to spend money on mining to provide the bq players with free bitcoin. wont happen.

**Comment by ScienceDemon** [comment]
@syrianrue , @theraccoonbear and @explodi , nevermind then: i was going to mine myself then transfer a small SOME to the loot wallet. keywords being myself and some. sorry for bothering you guys. other unfortunate thing was that I don't have proper mining hardware. so yeah.

**Comment by ScienceDemon** [comment]
i might go get some mining hardware, though.
