### ISSUE TITLE
New players without compass get trapped

### ISSUE THREAD

**Issue by doncullen** [bitquest/bitquest#205]
IF a new player joins the server, explores the Market, heads to the area under the tree farm (the mega map area that has stairs leading to bedrock [-171 1 16]) while having no compass, they get trapped in the bedrock with no way out -- even worse if nobody is able to help the new player.  Not a good starting experience.  I'm still trapped there at the time of this post.  There's five players on, and all of them are unable to help or nonresponsive. 

Tried using the /kill command to die and respawn back at world spawn, seems that's disabled.  It should be OK for players to commit suicide to be sent back to world spawn point, or at least allow a basic TP command that sends people back to the world spawn point.

**Comment by dildosex** [comment]
yh

**Comment by doncullen** [comment]
Update: olizbu was able to hunt me down and toss a compass my way.  Before someone asks, yes, I checked the compass dispenser prior to exploring, and it was empty.  Ditto for bed and sword dispenser.

**Comment by theraccoonbear** [comment]
I don't totally disagree, but 1) if you don't read the signs at the start, you probably are not prepared to play, and 2) you will starve, eventually.

I suspect the annoyance of waiting to starve will serve as a great educational aid.

**Comment by dildosex** [comment]
but if ur at a hole u wont die

**Comment by theraccoonbear** [comment]
If you move around and jump, you will starve. I get it, it takes time and it's annoying, but it will work.

**Comment by AltQuest** [comment]
Add this to onPlayerLogin() in EntityEvents.java:

if(!(BitQuest.REDIS.exists("name:"+player.getUniqueId().toString()))) {
	player.getInventory().addItem(new ItemStack(Material.COMPASS,1));
        player.sendMessage(ChatColor.GREEN + "Use a Compass to Teleport back here to spawn.");
}

**Comment by AltQuest** [comment]
https://github.com/bitquest/bitquest/pull/241 has a fix for this also. it gives new players a compass

**Comment by AltQuest** [comment]
this can be closed i think?
