### ISSUE TITLE
I am looking for a developer for bitquest.

### ISSUE THREAD

**Issue by crankycrypto** [bitquest/bitquest#207]
Hello fellow Bitquest folks.

I am a crypto day trader and an internet marketer.

I have set up a bitquest server and it isn't working completely.

I would like to hire and/or partner with a developer to set up the server and admin.

I have 10+ years marketing experience, 3 twitch professional gamers with a huge flowing and another professional gamer with 17K followers on instangram. 

I am interested in either paying to get it up correctly or partner up. 
I believe this Bitquest is better than crypto kitties and it just needs to be market properly.

**Comment by theraccoonbear** [comment]
This is really not the right forum for a job/business offer.  This is a code repository for issue (bug/feature/etc) tracking.  I would personally suggest posting to the BQ reddit, Slack, or Discord.

**Comment by explodi** [comment]
This space is used for discussing and review code issues and not a contact form. You can email me at bitquest@bitquest.co if you want help setting up your bitquest server

**Comment by crankycrypto** [comment]
Gottcha thanks.
