### ISSUE TITLE
Land transfer is buggy af

### ISSUE THREAD

**Issue by dildosex** [bitquest/bitquest#208]
/land transfer not working properly (atleast for longer usernames), sign is limited to 15 characters. Sign with ^abandon^ got a pretty big delay as well.

**Comment by sicixevu** [comment]
lost out on many of land because of this, thanks devs. Been more than a month and not even a reply,

**Comment by williamronn** [comment]
#216 think it got fixed with this Pull request

**Comment by AltQuest** [comment]
this is current code:  "} else if (name.startsWith("transfer ") && name.length() > 9) {"

can this be closed also?
