### ISSUE TITLE
Minimum transaction is 2k doge

### ISSUE THREAD

**Issue by dildosex** [bitquest/bitquest#209]
Please decrease it to something like 50 or 100

**Comment by theraccoonbear** [comment]
Doge?  you mean BTC?  I believe the minimum is so high because the fees are so high.  Sending 50 bits w/ a 1000 bit fee is a little silly.

**Comment by dildosex** [comment]
I am talking about dogequest, its 2k doges

**Comment by theraccoonbear** [comment]
Why on earth are you posting about DogeQuest on the BitQuest repo?

**Comment by dildosex** [comment]
Didn't know that dogequest existed on github

**Comment by williamronn** [comment]
It runs on the same code so that's why explodi told up to post it here

**Comment by dildosex** [comment]
Yea, get ur ass up to date raccoon

**Comment by piotrulos** [comment]
Doge fee is usually only 1 Doge, so 2k is overkill, with that low fee it could even be only 10 doge minimum.

**Comment by explodi** [comment]
transfer limit on dogequest lowered to 100.
