### ISSUE TITLE
Sheep farm is broken

### ISSUE THREAD

**Issue by dildosex** [bitquest/bitquest#211]
Also, donnie and putin and probably vladimir sheeps are as well lost too!

**Comment by explodi** [comment]
Please post again without the offensive nickname. I won't go into the reasons why, but there are many. I will document this in a "rules" section of the website to be created. Thanks for understanding

**Comment by syrianrue** [comment]
DS, are you the one the bred 200 sheep at spawn? we try to keep the mob count below 50 or so to ease up on the lag.
