### ISSUE TITLE
bitcoind can't connected.

### ISSUE THREAD

**Issue by wakiyamap** [bitquest/bitquest#213]
Hi.
I want to set up a bitquest server, but I get the following error......

> bitquest  | [22:09:35 INFO]: Unknown command. Type "/help" for help.
> bitquest  | [22:09:35 INFO]: Checking blockchain info...
> bitquest  | [22:09:35 INFO]: http://localhost:18332
> bitquest  | [22:09:35 INFO]: problem connecting with bitcoin node
> bitquest  | [22:09:35 INFO]: java.net.ConnectException: Connection refused (Connection refused)

I have two question.
1.Which branch should I use?
2.Is this setting for bitcoin.conf correct?
```
server=1
rpcuser=bob
rpcpassword=hogehoge
testnet=3
rpcallowip=127.0.0.1
```

thanks

**Comment by Jorropo** [comment]
"Connection refused (Connection refused)" this isn't a bitquest error, your port are just close, verify bitcoind configuration (problem should be here)

**Comment by wakiyamap** [comment]
@Jorropo thanks

I solved.
I am executing `sudo docker-compose up` at startup.
I successfully added docker's address to rpcallowip in bitcoin.conf.
