### ISSUE TITLE
Failed to set the gamemode when trying to change to creative.

### ISSUE THREAD

**Issue by raspi0124** [bitquest/bitquest#219]
When I execute "/gamemode 1" it always returns me "Failed to set the gamemode of USERNAME".
How can I fix that? or where in this code defines that?

**Comment by explodi** [comment]
Are you running on docker? Did you set the ADMIN_UUID variable?

**Comment by raspi0124** [comment]
I'm not running on Docker and even I set ADMIN_UUID, still same result.
![image](https://user-images.githubusercontent.com/22224201/39477741-78bd7328-4d60-11e8-8682-c78dab1ba294.png)

**Comment by juanj** [comment]
Game mode was disable for security reasons. You can comment the line `222` of the file `EntityEvents.java` to re enable it.

**Comment by raspi0124** [comment]
Thanks!
