### ISSUE TITLE
How are new players supposed to get Bits to claim land?

### ISSUE THREAD

**Issue by SnowyMiner** [bitquest/bitquest#23]

**Comment by juanj** [comment]
All the players can get Bits by killing mobs.

**Comment by SnowyMiner** [comment]
Yes but,  that takes time. We shouldn't expect new players to hide in a small underground base until they get the loot, the loot is also rare. Players should be given a kit or a free chunk to begin with and then they can buy more chunks later.

**Comment by juanj** [comment]
Yes, I agree.
We should give players a free chunk plus an iron (or stone?) sword.
What you think about that @explodi ?

**Comment by Winglessss** [comment]
Wouldn't giving people free land devalue  everyone's land?

**Comment by Xeyler** [comment]
Giving each player their first plot free doesn't sound like a bad idea to me, perhaps it should be discussed?

**Comment by theraccoonbear** [comment]
I think that's a reasonable idea, provided we flag that free plot in some way and allow it to be auto-abandoned if the player doesn't stick around.  If there's no investment on the player's part, we'll have people join, claim a plot, and leave after an hour and never return, leaving claimed chunks that are forever out of circulation.

**Comment by CubeFromSpace** [comment]
That works, but maybe it would be possible to lower the levels that a zombie pigmen spawns at. I can hardly get anything from the nether because all the pigmen are around lvl 40. It's insanely hard to get loot.

**Comment by CubeFromSpace** [comment]
Also now I suggested about loot chests in #109

**Comment by CubeFromSpace** [comment]
Most likely, you could possibly transfer 200 bits into the wallet, and in the same way @theraccoonbear suggested (sort of), flag that player and take back the 200 bits if he/she decided to quit

**Comment by CubeFromSpace** [comment]
@explodi refined the system so that every mob drops loot, but in smaller amounts due to the new hybrid wallet system

**Comment by TheFirstSpirit** [comment]
Actually, not every mob drops loot... only every 20th about...

**Comment by theraccoonbear** [comment]
@TheFirstSpirit 1 in 10 https://github.com/bitquest/bitquest/blob/d3efd1a743ab062bb4a1b8718f2dbce9618c054f/src/main/java/com/bitquest/bitquest/EntityEvents.java#L463

**Comment by CubeFromSpace** [comment]
@thefirstspirit earlier you explained magnificently how it worked, being 2 in 20, but what I stated 5 days ago was before he edited the system. Before then, it was every mob drops loot in small amounts

**Comment by theraccoonbear** [comment]
@CubeFromSpace You're right.  It's been fiddled with recently. Looks like starting on the 22nd it was 1 in 20: https://github.com/bitquest/bitquest/commit/7d48852df18ecfed682aa7e8ad2aa21d3d7519c8

Previous to that, it looks like you always got loot from every mob kill *if* the loot wallet had more than the randomly determined number of loot bits in it.

When or if either of those changes were pushed to beta or prod, I'm not sure.  I haven't looked to see what sort of CI or deployment stuff might be setup.

**Comment by Burntuno** [comment]
@TheFirstSpirit , Player to Player transfer is almost here.  Then it will be easier to gets some bits to start game.  Players usually make easy trades with new active players to help build community.  Loot has to be rare since it is only available if players spend bits shopping.  Once wallet features complete, many more bits will be passing around to enjoy the game.

**Comment by TheFirstSpirit** [comment]
If the server by default had 1 million bitcoins... which is about 1 trillion bits... that would definitely be enough.

**Comment by CubeFromSpace** [comment]
That would be worth about 1 BILLION DOLLARS

Seriously, that's stupid
