### ISSUE TITLE
Require test

### ISSUE THREAD

**Issue by Jorropo** [bitquest/bitquest#230]
https://github.com/bitquest/bitquest/blob/32691b8751595d582e9758cf565cc4cd5f2640db/src/main/java/com/bitquest/bitquest/BitQuest.java#L273
A "new" is supposed be before "java.util.Base64.getEncoder()" (This code shouldn't compile but it does).

**Comment by theraccoonbear** [comment]
pretty sure that's a static method and not a constructor

**Comment by juanj** [comment]
Indeed. Is a static method https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getEncoder--

**Comment by Jorropo** [comment]
Ok, thx I wasn't knowing (my english is so Frenchly) that.
I close.
