### ISSUE TITLE
fix golden apple price

### ISSUE THREAD

**Issue by catapim** [bitquest/bitquest#234]
the golden apple (not enchanted) costs 20 doge, not 5 as announced.

**Comment by catapim** [comment]
in doge, villagers say it costs 5, but when you purchase, the price is 20.

**Comment by AltQuest** [comment]
I see 2 possible fixes. 
1) need to get enchantment data for apple when checking items. If enchanted than 20 if not than 5. 
2) Or just remove 1 of the apples..

**Comment by catapim** [comment]
we removed one apple. @explodi fixed it. ty all.
