### ISSUE TITLE
create HelloWorldCommand

### ISSUE THREAD

**Issue by catapim** [bitquest/bitquest#236]

**Comment by Jorropo** [comment]
why it should ?

**Comment by AltQuest** [comment]
What??? No description??? What's going on here???

**Comment by catapim** [comment]
just to show new contributors the structure of a new command in case somebody wants to contribute. of course it won't have effects in the game. i will do it so don't worry.

**Comment by AltQuest** [comment]
whats the point of this? do you wnat a literal /helloworld ? and it just gives a bunch of server info??? i could do this...

**Comment by AltQuest** [comment]
I can do it no problem. I just need to know what is expected of the command?
/helloworld
"Welcome to servername the currency is whatever"
"Here are some useful commands"
"You can get loot this way"
Idk what is wanted for the command? The more info the better can take stuff put if too much.

**Comment by AltQuest** [comment]
Or is it not that. Is it literally like a ghost command just as an example? I'm just not understanding what the use is...
