### ISSUE TITLE
mods should be able to emergency /stop the server

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#24]

**Comment by RagingMouser** [comment]
What op level are mods currently? Is this a request for a configuration change or a way to let lower level ops have access to the /stop command?

**Comment by RagingMouser** [comment]
I've implemented this functionality in an existing pull request  (#3).  Changeset is [here](https://github.com/RagingMouser/bitquest/commit/21bb795ad3ea5852d27c1d8f41134d443fdc7eb0).

**Comment by RagingMouser** [comment]
Note: mods do not have direct access to the /stop command. Instead, mods of any level regardless of their op levels now have a /emergencystop command. It effectively does the same thing.
