### ISSUE TITLE
Multiple currencies on one server

### ISSUE THREAD

**Issue by BrightSkyz** [bitquest/bitquest#240]
I am suggesting that this adds support for multiple cryptocurrencies on one server, basically on the sidebar it will show all of them that are setup for the server and it shows balance. Another change would be adding a /change [currency] command which changes the currency you earn.

**Comment by Jorropo** [comment]
I all ready thinking about that but this will be very difficult.

**Comment by AltQuest** [comment]
This is actually something I've been wprking on. I already have a test server but not complete. It uses /currency <emerald|btc|ltc|doge> I'm trying to figure out a better way to code it more dynamically but some of that code could already be used to change between emeralds and btc..
