### ISSUE TITLE
Three ideas

### ISSUE THREAD

**Issue by CNKManga** [bitquest/bitquest#242]
1) right click on a bed while holding a compass to change where the compass teleports you similar to world of warcraft
2) a sponge version of the plugin
3) place a bed in each town for the first idea.

**Comment by AltQuest** [comment]
For #1 I'm considering making it so the first teleport location is free, and can add more for bits or whatever.

**Comment by CNKManga** [comment]
i think the price of extra player teleport locations will increase the more they have, but it's up to you.

**Comment by CNKManga** [comment]
oh, and a /compass command that does this:
1. checks to see if a player has any compasses in their inventory
either 2a. if a compass is found, it wont add a compass to their inventory
or 2b. if they dont have a compass in their inventory, it will add a compass to their inventory
after 2b. 3. there's a cooldown where they cant use the command for some time probably 24 hours

**Comment by AltQuest** [comment]
There is a /spawn command. So technically compasses could be removed for that aspect. But I think is left in for various reasons. I personally use my compass instead of /spawn

**Comment by explodi** [comment]
closing this issue and opening a new one for each idea
