### ISSUE TITLE
REDIS - SQL change?

### ISSUE THREAD

**Issue by AltQuest** [bitquest/bitquest#247]
just concerned for anyone running a previous server, if they would be able to upgrade smoothly? are the transfer tools going to stay in?

**Comment by explodi** [comment]
All user account information will be stored in PostgreSQL to allow better secirity and point-in-time backups. 
The bitquest Docker image supports the automatic creation of a instance+database via links (check the docker-compose.yml file for an example)

Managed databses like Amazon RDS should also work with environment variables.
