### ISSUE TITLE
More things to do with bitcoin in game (also additional revenue sources)

### ISSUE THREAD

**Issue by RagingMouser** [bitquest/bitquest#25]
You can get it from monsters and spend it claiming land, but what else can you do with it? A few ideas:
- Allow users to auction off their property to each other. 24/48 hr auctions with the winner getting the property and the server taking a percentage.
- Rail/teleporter tax. Have a railway or teleporter system throughout the major populated portions of the map. Users who have made a one-time donation or periodic donation get to use the public transportation system.
- Let users spend bitcoin to unlock a backpack plugin ([example](http://dev.bukkit.org/bukkit-plugins/backpack/))

**Comment by Xeyler** [comment]
I've thought about the first idea for a while. I think its a good idea, but that it shouldn't be an auction. Players should just be able to offer an amount of bits for a piece of land, and I suppose we could apply a small tax if necessary.

The second idea is new, though. I suppose we could sell permanent tickets that players could use to gain access to rails. We may discuss it further.

The third idea, though, is probably a little too out there. It wouldn't be too hard to implement, but we like to stay as vanilla as we can.

**Comment by RagingMouser** [comment]
I see. The only reason I thought of backpacks is since the claiming process is not clear at first and new users will quickly run out of secure places to store their things.

**Comment by Winglessss** [comment]
I was thinking a mail system would be great, mailboxes at properties, or ways to virtually send items alongside bits.

**Comment by Winglessss** [comment]
Server would charge a fee of course

**Comment by CubeFromSpace** [comment]
Someone on slack wanted land auctions. Don't remember who

**Comment by syrianrue** [comment]
well land buying/selling could be a great feature as right now theres no real market right now. there no way to list or advertise plots, find people who might want to sell a plot, and both buyer and seller have to be online.

land speculation seemed to work really well for secondlife. and it gives people something unique to buy, other than hoarding more diamonds/other generic blocks.
