### ISSUE TITLE
Renting lands

### ISSUE THREAD

**Issue by Arpetuos** [bitquest/bitquest#250]
Here is a new idea for Bitquest / Dogequest.

**People may be able to lease their claims, or a space in their claim (although the second option seems difficult to code) for a monthly rent.**

This upgrade would allow players to use the interesting claims especially near spawn, and inactives players can still have their lands, but while they are not using them, it can be useful to someone else, while making some doge for when they are active again.

Plus, it incentivizes people to claim and rent interesting lands. This maneuver may increase the market value of a chunk. Selling a chunk for an higher price than the buying price should be easier, because of the possible ROI.

In addition, begginers will be able to have a private land for their chests for less than the incoming 100 DOGE / Bit price, which is expensive, even more if they do not deposit.

I think the renting process should be private, so the server does not lease any lend. However, there could be a 20% tax on rents, for example. So, if the rent is 10 bits / months, this would create a 2 bit revenue for the server, and a 8 bit revenue for the player.

Any reactions ?

**Comment by Arpetuos** [comment]
One main principle in Economics, is : the more the money flows, the more value is added. Moving form one hand to another, the money will have more chance to be spent in the shop, or leasers will buy new lands with the rents.

**Comment by AltQuest** [comment]
i like this idea... have thought about it before... would need to be some sort of sign implementation. so maybe sign has:
"$days $price
X from-to
Y from-to
Z from-to"
and maybe have to click the sign 2 times to confirm. like first click with bell & notice in chat to click again to accept...
