### ISSUE TITLE
- lag and rubberbanding -

### ISSUE THREAD

**Issue by AltQuest** [bitquest/bitquest#257]
this has gotten worse since the last patch. I have had several instances where I just walk over to the Welcome Center from spawn and at any one point I just kind of "stutter" in place as I can no longer move forward. This lasts from about 10 seconds to about 30 seconds now. It's really bad with the Spooky Event going on. This is not limited to the areas around spawn. I have an area about 8k out and I still get the same "lag stutter" out there as well.
Along with that last thing about lag, I think the server has actually restarted / reloaded about 3 times in a short time frame as it has booted me off or just becomes unavailable if I relog to try and get away from the lag. In my server list it does show it's not pingable. Even if I refresh the list a few times. It does come back up but it's just a weird down time.

**Comment by QuintLeo** [comment]
This is probably part of the same issue as 256.
