### ISSUE TITLE
Special enchantments (Not vanilla for crypto villagers)

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#261]

**Comment by syrianrue** [comment]
theres plenty of things you could add this way. a pickaxe that gives you haste 3 while holding it. a walking stick that gives you speed 3 while holding it. a stick with knockback 20. turn off keep inventory, but sell an item that allows keep inventory on death, or maybe keep buffs on death. armor that adds resistance buff >3. a hold item that gives luck. efficiency 6 books.

**Comment by AltQuest** [comment]
Keepinvintory needs to be true becuse it would be unfair for a player to buy something at the market and lose it because of that.
