### ISSUE TITLE
No /home or /bed ?

### ISSUE THREAD

**Issue by AltQuest** [bitquest/bitquest#274]
-ash
oh, might want to open up a github issue. theres no /home or /bed command

**Comment by AlitheiaLynn** [comment]
SO FAR - The /home command has been working beautifully on both Doge and Bit. At least I haven't heard of anyone getting tp'd to anywhere random or anything like that.

Also /spawn has been working wonderful as well.

Both work fine from Nether and The End. :)

**Comment by syrianrue** [comment]
yes, you are correct. this is corrected and the issue should be closed

**Comment by masecla22** [comment]
You can use an ender eye to teleport yourself to the bed and a compass to teleport to spawn. Both can be crafted or purchased from a villager.

**Comment by AlitheiaLynn** [comment]
Actually neither of those items work any further. Both /home gets you to bed and /spawn get you to spawn. There is no longer need for eye of ender or compass. :)

This whole thing is now old and needs to be closed :)

**Comment by masecla22** [comment]
Ah, I was just trying to get issues closed '._. 
@explodi This can be closed.

**Comment by QuintLeo** [comment]
The only issue with /home now seems to be a Minecraft issue, where sometimes it will dismount you BELOW the level of your bed when porting to it, or below the level of your minecart when you dismount from it.
