### ISSUE TITLE
Can we have a suicide command?

### ISSUE THREAD

**Issue by RagingMouser** [bitquest/bitquest#28]
To teleport back to spawn takes time because we need to find a good way to die without damaging what we are wearing. If we had a suicide command we could easily teleport back to spawn without degrading our armour. If approved I can submit a pull request for this.

**Comment by juanj** [comment]
Well, we have the compass to do that.

**Comment by explodi** [comment]
Closed, but feel free to re open @RagingMouser

**Comment by StephenCasella** [comment]
Doesn't the compass take you to satoshi town?
