### ISSUE TITLE
Villager spawn rate needs to be lowered.

### ISSUE THREAD

**Issue by AlitheiaLynn** [bitquest/bitquest#280]
Is there a way to slow down the spawn rate of villagers at spawn (Doge and Bit) as they are over running spawn. I can kill them off on Doge (mod ability) but on bit it's just chaos. I have no powers there and they just keep spawning in happy as you please.

I would prefer not to use a kill all villager command as those villagers that people have worked hard to collect for their bases would rage if they just up and "poofed". I, for one, would be one of those sad saps that would have to resort to swearing at my screen if mine were to disappear on me. :)

**Comment by QuintLeo** [comment]
Have any of the mods checked to see if there's a broken villager spawner near spawn on DQ?
It seems like this issue started close to the time that Stevywar built their "market" near spawn.
