### ISSUE TITLE
Database backup system

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#298]
There should be a way for a server administrator to perform periodic "snapshots" of the redis rdb file. Snapshots could be uploaded to a s3-compatible object storage

**Comment by BitcoinJake09** [comment]
agreed, should be its own class file i feel. either the main BitQuest file can call it once a day or whatever or setup multiples and then the backup class can do its thing

could add extra compatibilities into the separate class also like add SQL export back into it or something..

**Comment by Nep-Soundfont** [comment]
can't you use a separate app installed on the same computer as the database for backing up the rdb to a folder?
 edit: if this does get added into the plugin, add an option to the plugin config for backup interval in hours?

**Comment by explodi** [comment]
Sadly, Mojang now prohibits integration of blockchain technology into Minecraft and this project will no longer be mantained :( feel free to fork at your own risk.

**Comment by Nep-Soundfont** [comment]
if thats the case, why not simply backup the master branch for archiving purposes and remove all the blockchain-related parts of the plugin? that way it still has the loot system, land claims, market, enemy levels etc.

**Comment by BitcoinJake09** [comment]
> if thats the case, why not simply backup the master branch for archiving purposes and remove all the blockchain-related parts of the plugin? that way it still has the loot system, land claims, market, enemy levels etc.

thats kinda what i was doing before with emeraldquest, but i didnt have much help there so i let it die :/
https://github.com/BitcoinJake09/EmeraldQuest

**Comment by Nep-Soundfont** [comment]
> > if thats the case, why not simply backup the master branch for archiving purposes and remove all the blockchain-related parts of the plugin? that way it still has the loot system, land claims, market, enemy levels etc.
> 
> thats kinda what i was doing before with emeraldquest, but i didnt have much help there so i let it die :/ https://github.com/BitcoinJake09/EmeraldQuest

oh yeah, i remember that, rather it used emeralds from the old 1.0 age with the new 2.0 features and without crypto, i'll repost #316 there
