### ISSUE TITLE
How can I compile and install the plugin correctly?

### ISSUE THREAD

**Issue by jcjms** [bitquest/bitquest#303]
Hey, I would like to install the BitQuest plugin on my Minecraft Bukkit server. But for that I have to compile it first. I tried Maven `mvn package` because I didn't know what `make -B jar` meant in the manual. This resulted in a .jar file which then did not work on the server (it issued error messages). I hope you can help me. Kind regards jcjms. Can you maybe do a short tutorial on setting up the plugin?

**Comment by BitcoinJake09** [comment]
you can compile with just maven but would still need environmental variables, the best way is to use docker/docker-compose
then you can do docker-compose build & docker-compose up
and if the docker-compose.yml file is all setup correctly then it should run..
keep in mind this plugin is experimental and is still in active development :D

**Comment by explodi** [comment]
I like the idea of a tutorial and I created issue #304.

Can you post yout output of the `make -B jar` command?

**Comment by BitcoinJake09** [comment]
i usually run:
mvn clean compile assembly:single

and it creates my jar in the target folder

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.573 s

**Comment by BitcoinJake09** [comment]
> Hey, I would like to install the BitQuest plugin on my Minecraft Bukkit server. But for that I have to compile it first. I tried Maven `mvn package` because I didn't know what `make -B jar` meant in the manual. This resulted in a .jar file which then did not work on the server (it issued error messages). I hope you can help me. Kind regards jcjms. Can you maybe do a short tutorial on setting up the plugin?

the other thing with running BitQuest jar on your server, is it does need to have the environmental variables set, a node to connect to, and a database

**Comment by explodi** [comment]
I think the best idea is to add a check for all the required environment variables and then fail with a helpful error message.

**Comment by PillagerMC** [comment]
Paper 1.16.5 supported?

**Comment by BitcoinJake09** [comment]
> Paper 1.16.5 supported?

im not familiar with paper, but BitQuest uses Bukkit, so i would assume no? but like i said not familiar with paper.
if paper supports bukkit, you should be able to run the compile BitQuest.jar if all environmental variables are set.

what would the benefit of paper be? why not just run spigot bukkit?

**Comment by explodi** [comment]
> Paper 1.16.5 supported?

Please create a new issue for this question.
