### ISSUE TITLE
Land I purchased purchased by someone else

### ISSUE THREAD

**Issue by SatoshiSpinster** [bitquest/bitquest#307]
Approximately 8 hours ago I bought a chunk at spawn and named it SpinsterSpawn.  The sign was placed at x = 0 y = 11 and z = 0.  My balance reflected that 10 doge was spent on the property.  I remember the game confirming because I had forgot about adding the space between Spinster and Spawn.

When I logged on today my balance still reflected the 10 doge gone, but I no longer owned the chunk at 0, 0.  It is now named doge.

Satoshi Spinster

**Comment by SatoshiSpinster** [comment]
Sorry, it wasn't spinster spawn, it was SatoshiSpawn.

**Comment by explodi** [comment]
Solved in #308
