### ISSUE TITLE
Purchased land reverts to wilderness

### ISSUE THREAD

**Issue by SatoshiSpinster** [bitquest/bitquest#308]
![2021-07-22_21 16 06](https://user-images.githubusercontent.com/87621183/126764422-f97e183f-5687-4efa-8a43-40bf1dc2276a.png)

Purchased more land, placed sign at -45  68  29.  At first it seemed to work fine.  Within a few hours it reverted to wilderness.

**Comment by explodi** [comment]
There is a problem with purchasing land via signs. To correctly purchase land, please use the command:

````
/land claim <name of your land>
````

All purchased lands with the `land` command are permanent, and purchasing via signs was disabled.
