### ISSUE TITLE
store land ownership on the blockchain

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#32]
Right now the BitQuest server(s) store land information on a REDIS server.

I am working on a way to store ownership data of game land chunks using the OpenAssets protocol, backed by the Bitcoin blokchain.

That means land owners will actually own a OpenAsset, making the cost of land ownership the mining fees to create the said asset. This can also enable the transfer of land ownership between players, across servers!

This issue is also an open call for developers to express the best way to accomplish this challenge

**Comment by Burntuno** [comment]
Possible problem could be a forced change of your game address, which happens, and then loosing access to all the land purchased before new address is assigned.  Also if blockchain explorer servers are down, land protections might not be in sync so fluidly.  Current system seems to have good flexibility with transfers and renames.  One can transfer often as needed with no chain interactions.

**Comment by theraccoonbear** [comment]
@explodi wouldn't this be significantly slower, having to hit some external API or looking up on the blockchain?  I would thing the only performant solution would involve caching info about chunk ownership (in something like REDIS) in which case you're right back where you started :P

**Comment by CubeFromSpace** [comment]
I think it could just scan the blockchain upon server start or restart, and load land ownership afterward, and then upload every new land claim onto the blockchain, and that would load instantly rather than upon the server start.

**Comment by CubeFromSpace** [comment]
Are you sure that will work with the current  system?
