### ISSUE TITLE
Have a public claim type, to keep public use, but prevent others from personally claiming it.

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#34]

**Comment by explodi** [comment]
(reported by burntone)

**Comment by Burntuno** [comment]
This is something that we could all use right away.  One idea is to be able to unlock your claim to all with something like ^public^ on sign and if needed putting ^private^ would reverse.  If a plot is ^public^, claiming would still be prevented.

**Comment by CubeFromSpace** [comment]
@explodi, this issue is inferior and useless now. This was added

**Comment by juanj** [comment]
This issue can be close.
