### ISSUE TITLE
Simple way to give up or un-claim land

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#35]
This would help sell plots or just abandon areas back to public use.  Original bits are still kept for server/loot and bitquest.  If Players should sell land, that would just be done on side with own wallets.  Simple ability to un-claim, just gives more options. (by Burntone)

**Comment by juanj** [comment]
This is prefered with a "sign" or with commands?
In general, is there any reason to avoid commands?

**Comment by explodi** [comment]
we should avoid commands whenever is possible, as we aim to keep the server as close to the original minecraft experience. 

some things like sending to outside wallets or banning players are implemented as commands because it's counter intuitive to do otherwise

**Comment by juanj** [comment]
This is implemented. This issue can be closed.

**Comment by Xeyler** [comment]
Fixed in #36
