### ISSUE TITLE
make a cool MOTD and logo

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#41]

**Comment by Xeyler** [comment]
I did this long ago
`\u00A76     [ \u00A76\u00A7lBit\u00A77\u00A7lQuest\u00A76 ]\n\u00A77             - Start your quest`

**Comment by Xeyler** [comment]
Here's the website's favicon resized to 64x64(the size a minecraft server icon needs to be). 
![server-icon](https://cloud.githubusercontent.com/assets/11788703/18901421/fc757832-8507-11e6-9138-a75d4b157254.png)

It was resized from 48x48, so it would obviously look a little better if you could get a 64x64 version. Anyways, the server will accept any png file that has a resolution of 64x64, is named "server-icon.png", and is in the server's root folder.

I think the MOTD and the icon are actually pretty important, so I support getting a server icon! Does this help?

**Comment by CubeFromSpace** [comment]
You can just use Minecraft color codes (§) and do that file suggestion Xeyler made. Pretty simple

**Comment by CubeFromSpace** [comment]
I know this sounds like a crude and cheap way to make a MOTD, but why not just add a simple MOTD plugin from bukkit (or similar page) to the server? It usually works well, and can be animated.

**Comment by CubeFromSpace** [comment]
@explodi I know this sounds like a crude and cheap way to make a MOTD, but why not just add a simple MOTD plugin from bukkit (or similar page) to the server? It usually works well, and can be animated.

**Comment by CubeFromSpace** [comment]
Why does nobody respond to my comments?
