### ISSUE TITLE
Issue running the server as localhost

### ISSUE THREAD

**Issue by Deathinflames** [bitquest/bitquest#43]
I am a huge fan of BQ and was wondering if i could request some help with running BQ on a localhost.

I've cloned the repo and got a BQ.jar compiled and running, however i am getting an error that i cannot seem to figure out.

http://pastebin.com/qT4fE95J

Any help would be greatly appreciated! Thanks

**Comment by weex** [comment]
@Deathinflames did you ever get this working?

**Comment by Deathinflames** [comment]
As a matter of fact i did, i used Linux to compile the .jar instead of windows. A Redis DB is also required, i had problems with the server assigning an address to players but that may have been fixed by now.

**Comment by SnowyMiner** [comment]
:3

**Comment by explodi** [comment]
Hi friends, please check the new README.md and tell me if this is the solution you were looking for. I only tested this on my main computer but will try to do Windows ASAP. Once we all agree I think we can close this issue.

**Comment by SnowyMiner** [comment]
:3
