### ISSUE TITLE
Blocking specific claim names

### ISSUE THREAD

**Issue by robmak3** [bitquest/bitquest#47]
Can we block claim names like "[ The Wilderness ]", "[The Wilderness]" and "[ Anonymous]", and maybe other names with profanity? People are starting to troll me with wilderness and anonymous, and 
names like "FUCK OFF" near spawn give a bad view of the server

**Comment by Xeyler** [comment]
I fully support this idea. Players should have a freedom of speech, but maybe less so with land names as it's more permanent than saying it in the chat.

At the very least, we should block "The Wilderness." That one is pretty devious.

**Comment by Airiellis** [comment]
It's not that big of a deal. This is an adult server and people will name their claim whatever they want it's their Bitcoin.

**Comment by explodi** [comment]
The wilderness should have a different notification color; Perhaps claimed lands are yellow and Wilderness is gray

**Comment by robmak3** [comment]
Been thinking,  what about having land names like FUCK OFF farther from spawn,  or name censors in specific areas.  A wilderness color should also be there,  even if people find a way to get around wilderness censoring,  there is the color.

**Comment by Winglessss** [comment]
I'm against censorship in any form. If we ban the word FUCK, where do we stop? I would like to see a free world of expression, leave it to users to enable a personal profanity filter.  Design a toggle-able profanity filter in settings. 

I do like the different color for"The Wilderness" though
