### ISSUE TITLE
Entities inside private chunks are not protected

### ISSUE THREAD

**Issue by explodi** [bitquest/bitquest#54]

**Comment by juanj** [comment]
The problem is not about animals but entities.
Entities need to be protected on protected land.

**Comment by Xeyler** [comment]
Armor stands and item frames fall under the entity category, so we should probably protect entities on claimed land.

**Comment by CubeFromSpace** [comment]
This is logical, but might be laggy because of checking every entity for its position and finding the owner and only allowing the owner to use it and whatnot.

**Comment by Xeyler** [comment]
That would be an inefficient way to handle it. 

Perhaps a better solution could be to check if an entity has been affected by a player, get the affected entity's location, then see if the play has permission over the chunk containing the entity's location.

That way, it only checks when an entity is affected, and it only checks one entity at a time.

**Comment by CubeFromSpace** [comment]
Lol yeah, I'm not the best coder here. (Sorry)

**Comment by Xeyler** [comment]
That's ok. Everyone here has started somewhere, @CubeFromSpace.

At first, it may seem that coding is simply memorizing methods of conventions, but it's also figuring out how to fit those methods together in the best way. It'll get easier as you practice.

**Comment by CubeFromSpace** [comment]
I know more about C++ and arduino stuff than Java.

**Comment by Burntuno** [comment]
Protecting entities is not an issue to regular players.  They understand the risks and hide the stuff the could be abused.  I sometimes wish we were able to kill things on claimed land.  It would let players interact more around towns or even Satoshi.

**Comment by theraccoonbear** [comment]
Agreed.  We provide what are effectively locks on doors.  If you lock your valuables (livestock included) in a building, it is protected, just like IRL.  Protecting all entities on claimed land is silly.  If someone pursues a "wild" animal onto claimed land, it suddenly would be owned by the land owner, and that's silly.  FWIW, if you can shoot an arrow at an animal, you can kill it, in my experience.

**Comment by juanj** [comment]
Perhaps animals can be left unprotected, but protect some specific entities like armor stands, item frames, lead knots and paintings (and ender crystals?).

**Comment by CubeFromSpace** [comment]
@explodi New idea, are you able to count all of those entities as passive mobs?

**Comment by Shiny-andKittens** [comment]
@explodi is this issue relevant anymore or does it need more investigation?
