### ISSUE TITLE
We need a MUCH BETTER mob system

### ISSUE THREAD

**Issue by robmak3** [bitquest/bitquest#65]
I right now have had my last words with this mob system... It's a piece of shit, and really needs to be toned down, and be similar to last server. 

Today, I joined, and spawned in dogetown today... Burntone says Hi, and starts to talk about the Mesa Line. All of a sudden, a creeper explodes and kills me while I'm replying to him. The mob system is getting so bad, can I just type a chat message without being blown up? And then I go back, and I decide to start to write signs for the info board I create for dogetown, and then I get one hit-killed by a lvl 36 zombie with some diamond armor, and a diamond sword... Are you kidding me? Once I respawn, BitRailer is fighting a zombie villager in the lobby of the INN. We have torches around the town, except in parts of the inn near ice. 

Bitquest used to be a place where fighting mobs wasn't required while you were building. I shouldn't be thinking about creating walls around a town, I should be thinking about having peace and making the town better and not have to waist my time on stupid walls. The next thing everyone is going to say is, the towns "FAR" out, and you then should be closer. Remember the last server, where noobs went to The Lost City and started out there? We should be to let players create everywhere, and not have these types of limits, which do not benefit the servers. 

I realize people want to fight mobs too. The game shouldn't have to be set to the highest difficulty of doom when you first join, this is realistic for an environment like the nether though. People who are to low of a level for the nether should have a diablo/TLF to play on. But I've had enough of this mob system, and it has to come to an end.

I realize people want to fight mobs too. The game shouldn't have to be set to the highest difficulty of doom when you first join, this is realistic for an environment like the nether though. People who are to low of a level for the nether should have a diablo/TLF to play on. You should have a choice when to fight and when to not. But I've had enough of this mob system, and it has to come to an end.

**Comment by RagingMouser** [comment]
If you were to summarize your complaint into an actionable suggestion, how would you recommend it be improved?

**Comment by CubeFromSpace** [comment]
This sorta happened recently in the 1.11.2 update. Now over world is level 1-3, and nether has less level 40 pigmen.

**Comment by CubeFromSpace** [comment]
This is set up so that the further From spawn, the higher the level. I might go to find the code later

**Comment by Shiny-andKittens** [comment]
I am attempting to fix it in the Nether and End with PR #165
