### ISSUE TITLE
If it can help (or correct if wrong)...

### ISSUE THREAD

**Issue by JuGre** [bitquest/bitquest#66]
Hi everyone! Since I know basically nothing about multiplayer servers, and I just found out this info (don't laugh please haha!!), maybe it might help someone else, so I share it... Also I put it in "questions" because if ever there's something wrong with using some of those, it would be good to know...

Thanks! Have a nice day everyone!

http://minecraft.gamepedia.com/Commands

oups... I tried the "tp" command and got that red message saying I wasn't allowed... then I have a wayyyyy more basic question: how do you manage to trade items with players far from you... In short, I'm a super basic player, I like to mine and kill mobs with my kids around (the reason why I got to a server, instead of paying for realms, I'd rather support the bitcoin server, good occasion to learn a few things about economy and how to be a good "social player" for my children too...), so often I have plenty of materials that I don't use, I see it might be helpful to some other players, but it's really painful for me to go find those players when I succeed and don't get killed 3 times on the way!!... thanks for your attention/patience :-)

**Comment by robmak3** [comment]
Pls post on reddit.com/r/bitquest

**Comment by JuGre** [comment]
OK thanks! sorry about that!

2016-06-05 13:02 GMT-04:00 robmak3 <notifications@github.com>:

**Comment by juanj** [comment]
Bitquest try to use the least amount of commands possible, so that page is not much help (but thanks for sharing).

You right click a [Compass](http://minecraft.gamepedia.com/Compass) to go to Satoshi Town and right click a [Ender Eye](http://minecraft.gamepedia.com/Eye_of_Ender) to go to your bed.
