### ISSUE TITLE
Game client issues on death

### ISSUE THREAD

**Issue by theraccoonbear** [bitquest/bitquest#68]
When I die and try to respawn, the process is stuck at 100% for a while and then I see a "Connection Lost / Kicked for flying (or related)" error message.  Exiting the server and attempting to reconnect  results in the process being stuck at 100% for a while again and then telling me "Connection Lost / Timed out".  To get back into the game I have to fully exit Minecraft and then reopen the game to connect again.

I'm not sure that it matters, but I'm on Ubuntu.  Here's some system info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

$ uname -a
Linux mimmisbrunnr 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by Xeyler** [comment]
@theraccoonbear, has this problem persisted?

**Comment by theraccoonbear** [comment]
No, I should have closed this before.  It was causing issues when I first started, but hasn't in some time now.
