### ISSUE TITLE
Horse goes invisible when getting off of it

### ISSUE THREAD

**Issue by SnowyMiner** [bitquest/bitquest#71]
There's a bug where your horse with saddle or armor will go invisible but, you can still here and see it's particles. This happens when getting off of the horse and I must log off and log back on to see the horse again. This is only a minor bug but, should be fixed in the future. #80

**Comment by Xeyler** [comment]
I've seen some very strange things with horses. Since I've started using 1.10, I don't see the entities riding horses. I believe this issue has to do with either Minecraft itself, or Spigot.
