### ISSUE TITLE
Trap Door's don't disappear when destroying the block they were attached to

### ISSUE THREAD

**Issue by SnowyMiner** [bitquest/bitquest#75]
I found out then when you break the block a trap door is on, the trap door doesn't go into an entity like it should. Instead it just floats there. This link is an example: http://imgur.com/QalHQ93

**Comment by Xeyler** [comment]
If it did, people would be able to grief by breaking a block to remove a trap door they don't have permission to remove.

**Comment by SnowyMiner** [comment]
Oh I see, I also just found out this isn't a bug. Haha
