### ISSUE TITLE
We need mayors

### ISSUE THREAD

**Issue by SnowyMiner** [bitquest/bitquest#76]
Bitquest 2 has only started a few months ago and we already have about 5 new towns! Emerald City, Sin City, Doge Town, Vanguard, and the new Mesa town. In this situation we should have mayors for each town. This will help prevent greifing and help newcomers find a settlement. I think the mayors should be the founder of each town. Such as Sin City's mayor could be PolarBear1000. I could be the mayor of my town, Vanguard.

**Comment by Winglessss** [comment]
What role/function would these mayor's fulfill?

**Comment by Winglessss** [comment]
I will take no part in any form of government! Bitcoin enables freedom from this type of ruling class!

**Comment by Airiellis** [comment]
If you wanna call yourself a mayor of a town just do it. I'm not sure this is something that would ever need to be coded. Clans will help make this mayor idea more posable.

**Comment by Xeyler** [comment]
I think mayors would fall under the clans category. A mayor would be equivalent to a clan leader. This will be discussed when we get to clans.
