### ISSUE TITLE
Server compiling error

### ISSUE THREAD

**Issue by devidao** [bitquest/bitquest#85]
I am getting these errors, how can i resolve them??

![error](https://cloud.githubusercontent.com/assets/5411643/17726732/8d73f3e8-645d-11e6-9634-c25dec9dafe2.png)

**Comment by Winglessss** [comment]
I believe you have to download BuildTools manually, move the file inside the folder you're working with and run Java -jar BuildTools.jar

**Comment by theraccoonbear** [comment]
Consider trying the suggestions immediately following... `* Try:` and see what additional useful output you get.

**Comment by devidao** [comment]
I tried --debug, but no more clear
![untitled](https://cloud.githubusercontent.com/assets/5411643/17744697/990e6112-64b1-11e6-88cc-c1b82a1146bc.png)

**Comment by Winglessss** [comment]
I see you are using jdk1.8.0_91
the newest version is 1.8.0_102

Maybe???

**Comment by devidao** [comment]
> I see you are using jdk1.8.0_91
> the newest version is 1.8.0_102
> 
> Maybe???
no, i updated but same result

**Comment by Winglessss** [comment]
Have you tried downloading Buildtools Jar manually?  
Download here: https://hub.spigotmc.org/jenkins/job/BuildTools/
Navigate to where you downloaded it, if you are using windows right click in folder and click on Git Bash here,
Download here: https://git-for-windows.github.io/
Then run java -jar BuildTools.jar inside Git-Bash

If that works you can go back to cmd line and run  the gradlew tasks.

**Comment by explodi** [comment]
There was a mistake in the documentation. The setupWorkspace task must run in bash on all platforms. In windows, bash can be installed in a number of ways, but I've tested the git-scm bash and it works. I've changed the documentation and now this is the recommended way for building in Windows.
