### ISSUE TITLE
Doing chunk transfer with (possibly bad?) username crashes plugins

### ISSUE THREAD

**Issue by theraccoonbear** [bitquest/bitquest#92]
Planting a sign on an owned plot with a `^transfer <username>^` can crash the plugins if the username lookup fails to correspond to a valid UUID.  Originally reported by Burntone, so these are details from our exchange.

**Comment by Xeyler** [comment]
After a quick investigation in this issue, I concluded that the UUID checker class we're using correctly handles invalid usernames. I tried transferring a plot to a player that doesn't exist, and it didn't crash BitQuest.

Perhaps this problem is related to something else?
