### ISSUE TITLE
Chat Filtering

### ISSUE THREAD

**Issue by Xeyler** [bitquest/bitquest#96]
I believe strongly in the freedom of speech, but there will always be times when a player decides to join the server and just repeat profanity, or simply spam the chat too much.

I also believe that we cannot in any way limit any player's ability to say whatever they want.

These two points considered, I think the only way we can give people a filter is by letting each player toggle their own filter. Players will be able to say whatever they want, but the other players won't have to listen.

Long story short, players should be able to ignore other players, or filter certain words exclusively from the text they receive. This will allow players to say what they want, and allow everyone else's chat to interpret it however they want.

_Also, as a vanity item, I think it would be fun if we replaced filtered words with something other than asterisks(_the star things*). For example, "go to hell" would be replaced with "Prithee transport thyself to tarnation". Personally, if this doesn't end up becoming a feature, I'll eventually make a client mod simply for the comedy.

**Comment by CubeFromSpace** [comment]
That is a hilarious idea, but people might think the person is crazy. I have some suggestions for this: use the asterisks, but add: <Player> meant to say <blah thingy thing>. Also, you could make it check every chat before sending it, and do anything to the stuff to be altered (the syntax is thought out for you🙂)

**Comment by CubeFromSpace** [comment]
That sounds like a hilarious idea.

**Comment by CubeFromSpace** [comment]
I think spamming is already filtered, and a warning is sent to the player too.

**Comment by CubeFromSpace** [comment]
@xeyler I think that PR was merged

**Comment by syrianrue** [comment]
i think this is on topic, but id like to suggest a simple fix in the meantime by enabling the /ignore <username> command

**Comment by CubeFromSpace** [comment]
You mean with CwazyMiner spamming profanity every few weeks?

**Comment by syrianrue** [comment]
no not just him. theres a couple annoying players on that i wouldnt mind ignoring. we were talking about it in public earlier but in this case the user was just saying the same thing 3x.  one of the other users even tried using /ignore before i mentioned that it should be enabled.

**Comment by CubeFromSpace** [comment]
@xeyler, there is a PR #112 that SORta adds this, but without the tarination part

**Comment by CubeFromSpace** [comment]
Wait I realized that that PR also references this issue. Sorry about that
