### ISSUE TITLE
Cobweb drops (minor issue)

### ISSUE THREAD

**Issue by CubeFromSpace** [bitquest/bitquest#99]
When I mine cobwebs with shears, it drops cobweb. If in regular Minecraft, it should drop 1 string.

**Comment by Xeyler** [comment]
"Cobwebs can be obtained by clipping them with shears. It will also drop itself if broken with a sword enchanted with Silk Touch. It will drop 1 piece of string if broken with a (non-Silk Touch) sword, if water touches or flows over it, or if a piston pushes it. It will drop nothing when broken using anything else."(See [Cobwebs on the Minecraft Wiki](http://minecraft.gamepedia.com/Cobweb))

It looks like this is, in fact, not an issue, but a feature of Minecraft.

**Comment by CubeFromSpace** [comment]
Oh :P sorry about that.
